[2025-07-29 05:54:10.414] [INFO    ] [PID:2855939-TID:140508872271680] [language_ops:120] [FUNC:setup_language_logging] ================================================================================
[2025-07-29 05:54:10.414] [INFO    ] [PID:2855939-TID:140508872271680] [language_ops:121] [FUNC:setup_language_logging] LANGUAGE DEBUG LOGGING INITIALIZED
[2025-07-29 05:54:10.415] [INFO    ] [PID:2855939-TID:140508872271680] [language_ops:122] [FUNC:setup_language_logging] Operations log: /home/hdmsofob/gaddisa/logs/language_operations.log
[2025-07-29 05:54:10.415] [INFO    ] [PID:2855939-TID:140508872271680] [language_ops:123] [FUNC:setup_language_logging] Error log: /home/hdmsofob/gaddisa/logs/language_errors.log
[2025-07-29 05:54:10.415] [INFO    ] [PID:2855939-TID:140508872271680] [language_ops:124] [FUNC:setup_language_logging] Debug log: /home/hdmsofob/gaddisa/logs/language_debug.log
[2025-07-29 05:54:10.416] [INFO    ] [PID:2855939-TID:140508872271680] [language_ops:125] [FUNC:setup_language_logging] ================================================================================
[2025-07-29 05:54:10.416] [INFO    ] [PID:2855939-TID:140508872271680] [language_ops.emergency_bot.telegram_bot.language_bridge:26] [FUNC:<module>] Language bridge module initialized with debug logging
[2025-07-29 05:54:33.618] [ERROR   ] [PID:2855939-TID:140508872271680] [language_ops.database:217] [FUNC:log_database_operation] DB_SELECT_FAILED: UserProfile for user 386787633 fields=['language'] - None
[2025-07-29 05:54:33.621] [ERROR   ] [PID:2855939-TID:140508872271680] [language_ops.database:217] [FUNC:log_database_operation] DB_SELECT_FAILED: UserProfile for user 386787633 fields=['language'] - no such column: accounts_userprofile.latitude
[2025-07-29 05:54:33.622] [ERROR   ] [PID:2855939-TID:140508872271680] [language_ops.emergency_bot.telegram_bot.language_bridge:83] [FUNC:get_user_language_async] Error getting user language for 386787633: no such column: accounts_userprofile.latitude
Traceback (most recent call last):
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: accounts_userprofile.latitude

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hdmsofob/gaddisa/emergency_bot/telegram_bot/language_bridge.py", line 71, in get_user_language_async
    language = await sync_to_async(get_user_language)(user_id_str)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/alt/python312/lib64/python3.12/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/gaddisa/emergency_bot/utils/translations.py", line 126, in get_user_language
    user = UserProfile.objects.get(telegram_id=telegram_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/models/query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/models/query.py", line 1935, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1622, in execute_sql
    cursor.execute(sql, params)
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: accounts_userprofile.latitude
[2025-07-29 05:54:33.623] [INFO    ] [PID:2855939-TID:140508872271680] [language_ops.emergency_bot.telegram_bot.language_bridge:84] [FUNC:get_user_language_async] Defaulting to English for user 386787633
[2025-07-29 05:56:20.520] [INFO    ] [PID:2869889-TID:140120735299392] [language_ops:120] [FUNC:setup_language_logging] ================================================================================
[2025-07-29 05:56:20.520] [INFO    ] [PID:2869889-TID:140120735299392] [language_ops:121] [FUNC:setup_language_logging] LANGUAGE DEBUG LOGGING INITIALIZED
[2025-07-29 05:56:20.520] [INFO    ] [PID:2869889-TID:140120735299392] [language_ops:122] [FUNC:setup_language_logging] Operations log: /home/hdmsofob/gaddisa/logs/language_operations.log
[2025-07-29 05:56:20.520] [INFO    ] [PID:2869889-TID:140120735299392] [language_ops:123] [FUNC:setup_language_logging] Error log: /home/hdmsofob/gaddisa/logs/language_errors.log
[2025-07-29 05:56:20.520] [INFO    ] [PID:2869889-TID:140120735299392] [language_ops:124] [FUNC:setup_language_logging] Debug log: /home/hdmsofob/gaddisa/logs/language_debug.log
[2025-07-29 05:56:20.520] [INFO    ] [PID:2869889-TID:140120735299392] [language_ops:125] [FUNC:setup_language_logging] ================================================================================
[2025-07-29 05:56:20.522] [INFO    ] [PID:2869889-TID:140120735299392] [language_ops.__main__:56] [FUNC:__init__] Language Debugger initialized
[2025-07-29 05:56:20.523] [INFO    ] [PID:2869889-TID:140120735299392] [language_ops.__main__:161] [FUNC:check_database_health] Checking database health
[2025-07-29 05:56:20.525] [INFO    ] [PID:2869889-TID:140120735299392] [language_ops.__main__:176] [FUNC:check_database_health] Database accessible. Total users: 8
[2025-07-29 05:56:20.526] [INFO    ] [PID:2869889-TID:140120735299392] [language_ops.__main__:182] [FUNC:check_database_health] Users with language en: 7
[2025-07-29 05:56:20.527] [INFO    ] [PID:2869889-TID:140120735299392] [language_ops.__main__:182] [FUNC:check_database_health] Users with language am: 0
[2025-07-29 05:56:20.527] [INFO    ] [PID:2869889-TID:140120735299392] [language_ops.__main__:182] [FUNC:check_database_health] Users with language om: 1
[2025-07-29 05:56:20.528] [INFO    ] [PID:2869889-TID:140120735299392] [language_ops.__main__:201] [FUNC:check_database_health] Found 8 users without data consent
[2025-07-29 06:20:57.499] [INFO    ] [PID:2992631-TID:140001314461504] [language_ops:120] [FUNC:setup_language_logging] ================================================================================
[2025-07-29 06:20:57.499] [INFO    ] [PID:2992631-TID:140001314461504] [language_ops:121] [FUNC:setup_language_logging] LANGUAGE DEBUG LOGGING INITIALIZED
[2025-07-29 06:20:57.499] [INFO    ] [PID:2992631-TID:140001314461504] [language_ops:122] [FUNC:setup_language_logging] Operations log: /home/hdmsofob/gaddisa/logs/language_operations.log
[2025-07-29 06:20:57.500] [INFO    ] [PID:2992631-TID:140001314461504] [language_ops:123] [FUNC:setup_language_logging] Error log: /home/hdmsofob/gaddisa/logs/language_errors.log
[2025-07-29 06:20:57.500] [INFO    ] [PID:2992631-TID:140001314461504] [language_ops:124] [FUNC:setup_language_logging] Debug log: /home/hdmsofob/gaddisa/logs/language_debug.log
[2025-07-29 06:20:57.500] [INFO    ] [PID:2992631-TID:140001314461504] [language_ops:125] [FUNC:setup_language_logging] ================================================================================
[2025-07-29 06:20:57.500] [INFO    ] [PID:2992631-TID:140001314461504] [language_ops.emergency_bot.telegram_bot.language_bridge:26] [FUNC:<module>] Language bridge module initialized with debug logging
[2025-07-29 06:21:41.900] [INFO    ] [PID:2998690-TID:140190523901760] [language_ops:120] [FUNC:setup_language_logging] ================================================================================
[2025-07-29 06:21:41.901] [INFO    ] [PID:2998690-TID:140190523901760] [language_ops:121] [FUNC:setup_language_logging] LANGUAGE DEBUG LOGGING INITIALIZED
[2025-07-29 06:21:41.901] [INFO    ] [PID:2998690-TID:140190523901760] [language_ops:122] [FUNC:setup_language_logging] Operations log: /home/hdmsofob/gaddisa/logs/language_operations.log
[2025-07-29 06:21:41.901] [INFO    ] [PID:2998690-TID:140190523901760] [language_ops:123] [FUNC:setup_language_logging] Error log: /home/hdmsofob/gaddisa/logs/language_errors.log
[2025-07-29 06:21:41.901] [INFO    ] [PID:2998690-TID:140190523901760] [language_ops:124] [FUNC:setup_language_logging] Debug log: /home/hdmsofob/gaddisa/logs/language_debug.log
[2025-07-29 06:21:41.901] [INFO    ] [PID:2998690-TID:140190523901760] [language_ops:125] [FUNC:setup_language_logging] ================================================================================
[2025-07-29 06:21:41.901] [INFO    ] [PID:2998690-TID:140190523901760] [language_ops.emergency_bot.telegram_bot.language_bridge:26] [FUNC:<module>] Language bridge module initialized with debug logging
[2025-07-29 06:21:53.841] [INFO    ] [PID:2998690-TID:140190523901760] [language_ops.emergency_bot.telegram_bot.language_bridge:172] [FUNC:language_button_callback] language_button_callback triggered by user 386787633 with data: setlang_am
[2025-07-29 06:21:53.878] [INFO    ] [PID:2998690-TID:140190523901760] [language_ops.emergency_bot.telegram_bot.language_bridge:201] [FUNC:language_button_callback] User 386787633 attempting to change language to: am
[2025-07-29 06:21:53.878] [INFO    ] [PID:2998690-TID:140190523901760] [language_ops.emergency_bot.telegram_bot.language_bridge:89] [FUNC:update_user_language_async] update_user_language_async called for user 386787633 with language am
[2025-07-29 06:21:53.879] [ERROR   ] [PID:2998690-TID:140190523901760] [language_ops.database:217] [FUNC:log_database_operation] DB_SELECT_FAILED: UserProfile for user 386787633 fields=['language'] - None
[2025-07-29 06:21:53.883] [ERROR   ] [PID:2998690-TID:140190523901760] [language_ops.database:217] [FUNC:log_database_operation] DB_SELECT_FAILED: UserProfile for user 386787633 fields=['language'] - no such column: accounts_userprofile.latitude
[2025-07-29 06:21:53.886] [ERROR   ] [PID:2998690-TID:140190523901760] [language_ops.emergency_bot.telegram_bot.language_bridge:83] [FUNC:get_user_language_async] Error getting user language for 386787633: no such column: accounts_userprofile.latitude
Traceback (most recent call last):
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: accounts_userprofile.latitude

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hdmsofob/gaddisa/emergency_bot/telegram_bot/language_bridge.py", line 71, in get_user_language_async
    language = await sync_to_async(get_user_language)(user_id_str)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/alt/python312/lib64/python3.12/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/gaddisa/emergency_bot/utils/translations.py", line 126, in get_user_language
    user = UserProfile.objects.get(telegram_id=telegram_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/models/query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/models/query.py", line 1935, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1622, in execute_sql
    cursor.execute(sql, params)
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: accounts_userprofile.latitude
[2025-07-29 06:21:53.887] [INFO    ] [PID:2998690-TID:140190523901760] [language_ops.emergency_bot.telegram_bot.language_bridge:84] [FUNC:get_user_language_async] Defaulting to English for user 386787633
[2025-07-29 06:21:53.887] [ERROR   ] [PID:2998690-TID:140190523901760] [language_ops.database:217] [FUNC:log_database_operation] DB_UPDATE_FAILED: UserProfile for user 386787633 fields=['language'] - None
[2025-07-29 06:21:53.888] [INFO    ] [PID:2998690-TID:140190196508416] [language_ops.emergency_bot.utils.translations:165] [FUNC:update_user_language] update_user_language called with telegram_id=386787633, language_code=am
[2025-07-29 06:21:53.888] [ERROR   ] [PID:2998690-TID:140190196508416] [language_ops.database:217] [FUNC:log_database_operation] DB_GET_OR_CREATE_FAILED: UserProfile for user 386787633 fields=['telegram_id', 'language'] - None
[2025-07-29 06:21:53.891] [ERROR   ] [PID:2998690-TID:140190196508416] [language_ops.emergency_bot.utils.translations:267] [FUNC:update_user_language] Error updating language for user 386787633: no such column: accounts_userprofile.latitude
Traceback (most recent call last):
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: accounts_userprofile.latitude

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hdmsofob/gaddisa/emergency_bot/utils/translations.py", line 189, in update_user_language
    existing_user = UserProfile.objects.get(telegram_id=telegram_id)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/models/query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/models/query.py", line 1935, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1622, in execute_sql
    cursor.execute(sql, params)
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: accounts_userprofile.latitude
[2025-07-29 06:21:53.891] [ERROR   ] [PID:2998690-TID:140190196508416] [language_ops.database:217] [FUNC:log_database_operation] DB_UPDATE_FAILED: UserProfile for user 386787633 fields=['language'] - Exception in update_user_language: no such column: accounts_userprofile.latitude
[2025-07-29 06:21:53.891] [ERROR   ] [PID:2998690-TID:140190196508416] [language_ops.language_change:192] [FUNC:log_user_language_change] LANGUAGE_CHANGE_FAILED: User 386787633 failed to change from 'unknown' to 'am' - Exception in update_user_language: no such column: accounts_userprofile.latitude
[2025-07-29 06:21:53.893] [ERROR   ] [PID:2998690-TID:140190196508416] [language_ops.emergency_bot.utils.translations:274] [FUNC:update_user_language] Full traceback: Traceback (most recent call last):
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: accounts_userprofile.latitude

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hdmsofob/gaddisa/emergency_bot/utils/translations.py", line 189, in update_user_language
    existing_user = UserProfile.objects.get(telegram_id=telegram_id)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/models/query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/models/query.py", line 1935, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1622, in execute_sql
    cursor.execute(sql, params)
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdmsofob/virtualenv/gaddisa/3.12/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: accounts_userprofile.latitude

[2025-07-29 06:21:53.893] [ERROR   ] [PID:2998690-TID:140190523901760] [language_ops.database:217] [FUNC:log_database_operation] DB_UPDATE_FAILED: UserProfile for user 386787633 fields=['language'] - update_user_language returned False
[2025-07-29 06:21:53.893] [ERROR   ] [PID:2998690-TID:140190523901760] [language_ops.language_change:192] [FUNC:log_user_language_change] LANGUAGE_CHANGE_FAILED: User 386787633 failed to change from 'en' to 'am' - update_user_language returned False
[2025-07-29 06:21:53.894] [ERROR   ] [PID:2998690-TID:140190523901760] [language_ops.emergency_bot.telegram_bot.language_bridge:132] [FUNC:update_user_language_async] Failed to update language for user 386787633: update_user_language returned False
[2025-07-29 06:21:53.894] [INFO    ] [PID:2998690-TID:140190523901760] [language_ops.emergency_bot.telegram_bot.language_bridge:206] [FUNC:language_button_callback] Language update result for user 386787633: success=False
[2025-07-29 06:21:53.894] [ERROR   ] [PID:2998690-TID:140190523901760] [language_ops.emergency_bot.telegram_bot.language_bridge:282] [FUNC:language_button_callback] Language update failed for user 386787633, showing error message
[2025-07-29 06:53:55.234] [INFO    ] [PID:3144008-TID:139770377262912] [language_ops:120] [FUNC:setup_language_logging] ================================================================================
[2025-07-29 06:53:55.234] [INFO    ] [PID:3144008-TID:139770377262912] [language_ops:121] [FUNC:setup_language_logging] LANGUAGE DEBUG LOGGING INITIALIZED
[2025-07-29 06:53:55.234] [INFO    ] [PID:3144008-TID:139770377262912] [language_ops:122] [FUNC:setup_language_logging] Operations log: /home/hdmsofob/gaddisa/logs/language_operations.log
[2025-07-29 06:53:55.234] [INFO    ] [PID:3144008-TID:139770377262912] [language_ops:123] [FUNC:setup_language_logging] Error log: /home/hdmsofob/gaddisa/logs/language_errors.log
[2025-07-29 06:53:55.234] [INFO    ] [PID:3144008-TID:139770377262912] [language_ops:124] [FUNC:setup_language_logging] Debug log: /home/hdmsofob/gaddisa/logs/language_debug.log
[2025-07-29 06:53:55.235] [INFO    ] [PID:3144008-TID:139770377262912] [language_ops:125] [FUNC:setup_language_logging] ================================================================================
[2025-07-29 06:53:55.235] [INFO    ] [PID:3144008-TID:139770377262912] [language_ops.emergency_bot.telegram_bot.language_bridge:26] [FUNC:<module>] Language bridge module initialized with debug logging
[2025-07-29 06:54:24.707] [INFO    ] [PID:3145359-TID:139953102849856] [language_ops:120] [FUNC:setup_language_logging] ================================================================================
[2025-07-29 06:54:24.707] [INFO    ] [PID:3145359-TID:139953102849856] [language_ops:121] [FUNC:setup_language_logging] LANGUAGE DEBUG LOGGING INITIALIZED
[2025-07-29 06:54:24.708] [INFO    ] [PID:3145359-TID:139953102849856] [language_ops:122] [FUNC:setup_language_logging] Operations log: /home/hdmsofob/gaddisa/logs/language_operations.log
[2025-07-29 06:54:24.708] [INFO    ] [PID:3145359-TID:139953102849856] [language_ops:123] [FUNC:setup_language_logging] Error log: /home/hdmsofob/gaddisa/logs/language_errors.log
[2025-07-29 06:54:24.708] [INFO    ] [PID:3145359-TID:139953102849856] [language_ops:124] [FUNC:setup_language_logging] Debug log: /home/hdmsofob/gaddisa/logs/language_debug.log
[2025-07-29 06:54:24.708] [INFO    ] [PID:3145359-TID:139953102849856] [language_ops:125] [FUNC:setup_language_logging] ================================================================================
[2025-07-29 06:54:24.709] [INFO    ] [PID:3145359-TID:139953102849856] [language_ops.emergency_bot.telegram_bot.language_bridge:26] [FUNC:<module>] Language bridge module initialized with debug logging
[2025-07-29 06:56:31.028] [INFO    ] [PID:3151039-TID:140078017369920] [language_ops:120] [FUNC:setup_language_logging] ================================================================================
[2025-07-29 06:56:31.029] [INFO    ] [PID:3151039-TID:140078017369920] [language_ops:121] [FUNC:setup_language_logging] LANGUAGE DEBUG LOGGING INITIALIZED
[2025-07-29 06:56:31.029] [INFO    ] [PID:3151039-TID:140078017369920] [language_ops:122] [FUNC:setup_language_logging] Operations log: /home/hdmsofob/gaddisa/logs/language_operations.log
[2025-07-29 06:56:31.029] [INFO    ] [PID:3151039-TID:140078017369920] [language_ops:123] [FUNC:setup_language_logging] Error log: /home/hdmsofob/gaddisa/logs/language_errors.log
[2025-07-29 06:56:31.030] [INFO    ] [PID:3151039-TID:140078017369920] [language_ops:124] [FUNC:setup_language_logging] Debug log: /home/hdmsofob/gaddisa/logs/language_debug.log
[2025-07-29 06:56:31.030] [INFO    ] [PID:3151039-TID:140078017369920] [language_ops:125] [FUNC:setup_language_logging] ================================================================================
[2025-07-29 06:56:31.030] [INFO    ] [PID:3151039-TID:140078017369920] [language_ops.emergency_bot.telegram_bot.language_bridge:26] [FUNC:<module>] Language bridge module initialized with debug logging
[2025-07-29 08:45:53.330] [INFO    ] [PID:3828431-TID:140640032847680] [language_ops:120] [FUNC:setup_language_logging] ================================================================================
[2025-07-29 08:45:53.331] [INFO    ] [PID:3828431-TID:140640032847680] [language_ops:121] [FUNC:setup_language_logging] LANGUAGE DEBUG LOGGING INITIALIZED
[2025-07-29 08:45:53.331] [INFO    ] [PID:3828431-TID:140640032847680] [language_ops:122] [FUNC:setup_language_logging] Operations log: /home/hdmsofob/gaddisa/logs/language_operations.log
[2025-07-29 08:45:53.331] [INFO    ] [PID:3828431-TID:140640032847680] [language_ops:123] [FUNC:setup_language_logging] Error log: /home/hdmsofob/gaddisa/logs/language_errors.log
[2025-07-29 08:45:53.331] [INFO    ] [PID:3828431-TID:140640032847680] [language_ops:124] [FUNC:setup_language_logging] Debug log: /home/hdmsofob/gaddisa/logs/language_debug.log
[2025-07-29 08:45:53.332] [INFO    ] [PID:3828431-TID:140640032847680] [language_ops:125] [FUNC:setup_language_logging] ================================================================================
[2025-07-29 08:45:53.332] [INFO    ] [PID:3828431-TID:140640032847680] [language_ops.emergency_bot.telegram_bot.language_bridge:26] [FUNC:<module>] Language bridge module initialized with debug logging
[2025-07-29 08:51:15.917] [INFO    ] [PID:3848048-TID:140688561223488] [language_ops:120] [FUNC:setup_language_logging] ================================================================================
[2025-07-29 08:51:15.917] [INFO    ] [PID:3848048-TID:140688561223488] [language_ops:121] [FUNC:setup_language_logging] LANGUAGE DEBUG LOGGING INITIALIZED
[2025-07-29 08:51:15.917] [INFO    ] [PID:3848048-TID:140688561223488] [language_ops:122] [FUNC:setup_language_logging] Operations log: /home/hdmsofob/gaddisa/logs/language_operations.log
[2025-07-29 08:51:15.917] [INFO    ] [PID:3848048-TID:140688561223488] [language_ops:123] [FUNC:setup_language_logging] Error log: /home/hdmsofob/gaddisa/logs/language_errors.log
[2025-07-29 08:51:15.918] [INFO    ] [PID:3848048-TID:140688561223488] [language_ops:124] [FUNC:setup_language_logging] Debug log: /home/hdmsofob/gaddisa/logs/language_debug.log
[2025-07-29 08:51:15.918] [INFO    ] [PID:3848048-TID:140688561223488] [language_ops:125] [FUNC:setup_language_logging] ================================================================================
[2025-07-29 08:51:15.918] [INFO    ] [PID:3848048-TID:140688561223488] [language_ops.emergency_bot.telegram_bot.language_bridge:26] [FUNC:<module>] Language bridge module initialized with debug logging
[2025-07-30 23:05:10.353] [INFO    ] [PID:1037653-TID:140382991521600] [language_ops:120] [FUNC:setup_language_logging] ================================================================================
[2025-07-30 23:05:10.353] [INFO    ] [PID:1037653-TID:140382991521600] [language_ops:121] [FUNC:setup_language_logging] LANGUAGE DEBUG LOGGING INITIALIZED
[2025-07-30 23:05:10.353] [INFO    ] [PID:1037653-TID:140382991521600] [language_ops:122] [FUNC:setup_language_logging] Operations log: /home/hdmsofob/gaddisa/logs/language_operations.log
[2025-07-30 23:05:10.353] [INFO    ] [PID:1037653-TID:140382991521600] [language_ops:123] [FUNC:setup_language_logging] Error log: /home/hdmsofob/gaddisa/logs/language_errors.log
[2025-07-30 23:05:10.354] [INFO    ] [PID:1037653-TID:140382991521600] [language_ops:124] [FUNC:setup_language_logging] Debug log: /home/hdmsofob/gaddisa/logs/language_debug.log
[2025-07-30 23:05:10.354] [INFO    ] [PID:1037653-TID:140382991521600] [language_ops:125] [FUNC:setup_language_logging] ================================================================================
[2025-07-30 23:05:10.354] [INFO    ] [PID:1037653-TID:140382991521600] [language_ops.emergency_bot.telegram_bot.language_bridge:26] [FUNC:<module>] Language bridge module initialized with debug logging
[2025-07-30 23:05:16.478] [INFO    ] [PID:1038046-TID:140080490862400] [language_ops:120] [FUNC:setup_language_logging] ================================================================================
[2025-07-30 23:05:16.479] [INFO    ] [PID:1038046-TID:140080490862400] [language_ops:121] [FUNC:setup_language_logging] LANGUAGE DEBUG LOGGING INITIALIZED
[2025-07-30 23:05:16.479] [INFO    ] [PID:1038046-TID:140080490862400] [language_ops:122] [FUNC:setup_language_logging] Operations log: /home/hdmsofob/gaddisa/logs/language_operations.log
[2025-07-30 23:05:16.479] [INFO    ] [PID:1038046-TID:140080490862400] [language_ops:123] [FUNC:setup_language_logging] Error log: /home/hdmsofob/gaddisa/logs/language_errors.log
[2025-07-30 23:05:16.479] [INFO    ] [PID:1038046-TID:140080490862400] [language_ops:124] [FUNC:setup_language_logging] Debug log: /home/hdmsofob/gaddisa/logs/language_debug.log
[2025-07-30 23:05:16.479] [INFO    ] [PID:1038046-TID:140080490862400] [language_ops:125] [FUNC:setup_language_logging] ================================================================================
[2025-07-30 23:05:16.480] [INFO    ] [PID:1038046-TID:140080490862400] [language_ops.emergency_bot.telegram_bot.language_bridge:26] [FUNC:<module>] Language bridge module initialized with debug logging
[2025-07-30 23:05:27.190] [INFO    ] [PID:1040906-TID:140624928614208] [language_ops:120] [FUNC:setup_language_logging] ================================================================================
[2025-07-30 23:05:27.190] [INFO    ] [PID:1040906-TID:140624928614208] [language_ops:121] [FUNC:setup_language_logging] LANGUAGE DEBUG LOGGING INITIALIZED
[2025-07-30 23:05:27.191] [INFO    ] [PID:1040906-TID:140624928614208] [language_ops:122] [FUNC:setup_language_logging] Operations log: /home/hdmsofob/gaddisa/logs/language_operations.log
[2025-07-30 23:05:27.191] [INFO    ] [PID:1040906-TID:140624928614208] [language_ops:123] [FUNC:setup_language_logging] Error log: /home/hdmsofob/gaddisa/logs/language_errors.log
[2025-07-30 23:05:27.191] [INFO    ] [PID:1040906-TID:140624928614208] [language_ops:124] [FUNC:setup_language_logging] Debug log: /home/hdmsofob/gaddisa/logs/language_debug.log
[2025-07-30 23:05:27.191] [INFO    ] [PID:1040906-TID:140624928614208] [language_ops:125] [FUNC:setup_language_logging] ================================================================================
[2025-07-30 23:05:27.192] [INFO    ] [PID:1040906-TID:140624928614208] [language_ops.emergency_bot.telegram_bot.language_bridge:26] [FUNC:<module>] Language bridge module initialized with debug logging
[2025-07-30 23:05:42.564] [INFO    ] [PID:1042802-TID:139627313186624] [language_ops:120] [FUNC:setup_language_logging] ================================================================================
[2025-07-30 23:05:42.564] [INFO    ] [PID:1042802-TID:139627313186624] [language_ops:121] [FUNC:setup_language_logging] LANGUAGE DEBUG LOGGING INITIALIZED
[2025-07-30 23:05:42.564] [INFO    ] [PID:1042802-TID:139627313186624] [language_ops:122] [FUNC:setup_language_logging] Operations log: /home/hdmsofob/gaddisa/logs/language_operations.log
[2025-07-30 23:05:42.565] [INFO    ] [PID:1042802-TID:139627313186624] [language_ops:123] [FUNC:setup_language_logging] Error log: /home/hdmsofob/gaddisa/logs/language_errors.log
[2025-07-30 23:05:42.567] [INFO    ] [PID:1042802-TID:139627313186624] [language_ops:124] [FUNC:setup_language_logging] Debug log: /home/hdmsofob/gaddisa/logs/language_debug.log
[2025-07-30 23:05:42.567] [INFO    ] [PID:1042802-TID:139627313186624] [language_ops:125] [FUNC:setup_language_logging] ================================================================================
[2025-07-30 23:05:42.567] [INFO    ] [PID:1042802-TID:139627313186624] [language_ops.emergency_bot.telegram_bot.language_bridge:26] [FUNC:<module>] Language bridge module initialized with debug logging
[2025-07-30 23:05:51.047] [INFO    ] [PID:1043026-TID:139720424724288] [language_ops:120] [FUNC:setup_language_logging] ================================================================================
[2025-07-30 23:05:51.047] [INFO    ] [PID:1043026-TID:139720424724288] [language_ops:121] [FUNC:setup_language_logging] LANGUAGE DEBUG LOGGING INITIALIZED
[2025-07-30 23:05:51.048] [INFO    ] [PID:1043026-TID:139720424724288] [language_ops:122] [FUNC:setup_language_logging] Operations log: /home/hdmsofob/gaddisa/logs/language_operations.log
[2025-07-30 23:05:51.048] [INFO    ] [PID:1043026-TID:139720424724288] [language_ops:123] [FUNC:setup_language_logging] Error log: /home/hdmsofob/gaddisa/logs/language_errors.log
[2025-07-30 23:05:51.048] [INFO    ] [PID:1043026-TID:139720424724288] [language_ops:124] [FUNC:setup_language_logging] Debug log: /home/hdmsofob/gaddisa/logs/language_debug.log
[2025-07-30 23:05:51.048] [INFO    ] [PID:1043026-TID:139720424724288] [language_ops:125] [FUNC:setup_language_logging] ================================================================================
[2025-07-30 23:05:51.048] [INFO    ] [PID:1043026-TID:139720424724288] [language_ops.emergency_bot.telegram_bot.language_bridge:26] [FUNC:<module>] Language bridge module initialized with debug logging
[2025-07-30 23:06:02.975] [INFO    ] [PID:1043241-TID:140274043422528] [language_ops:120] [FUNC:setup_language_logging] ================================================================================
[2025-07-30 23:06:02.975] [INFO    ] [PID:1043241-TID:140274043422528] [language_ops:121] [FUNC:setup_language_logging] LANGUAGE DEBUG LOGGING INITIALIZED
[2025-07-30 23:06:02.975] [INFO    ] [PID:1043241-TID:140274043422528] [language_ops:122] [FUNC:setup_language_logging] Operations log: /home/hdmsofob/gaddisa/logs/language_operations.log
[2025-07-30 23:06:02.975] [INFO    ] [PID:1043241-TID:140274043422528] [language_ops:123] [FUNC:setup_language_logging] Error log: /home/hdmsofob/gaddisa/logs/language_errors.log
[2025-07-30 23:06:02.975] [INFO    ] [PID:1043241-TID:140274043422528] [language_ops:124] [FUNC:setup_language_logging] Debug log: /home/hdmsofob/gaddisa/logs/language_debug.log
[2025-07-30 23:06:02.976] [INFO    ] [PID:1043241-TID:140274043422528] [language_ops:125] [FUNC:setup_language_logging] ================================================================================
[2025-07-30 23:06:02.976] [INFO    ] [PID:1043241-TID:140274043422528] [language_ops.emergency_bot.telegram_bot.language_bridge:26] [FUNC:<module>] Language bridge module initialized with debug logging
[2025-07-30 23:44:07.080] [INFO    ] [PID:1181727-TID:140384139224896] [language_ops:120] [FUNC:setup_language_logging] ================================================================================
[2025-07-30 23:44:07.081] [INFO    ] [PID:1181727-TID:140384139224896] [language_ops:121] [FUNC:setup_language_logging] LANGUAGE DEBUG LOGGING INITIALIZED
[2025-07-30 23:44:07.081] [INFO    ] [PID:1181727-TID:140384139224896] [language_ops:122] [FUNC:setup_language_logging] Operations log: /home/hdmsofob/gaddisa/logs/language_operations.log
[2025-07-30 23:44:07.082] [INFO    ] [PID:1181727-TID:140384139224896] [language_ops:123] [FUNC:setup_language_logging] Error log: /home/hdmsofob/gaddisa/logs/language_errors.log
[2025-07-30 23:44:07.082] [INFO    ] [PID:1181727-TID:140384139224896] [language_ops:124] [FUNC:setup_language_logging] Debug log: /home/hdmsofob/gaddisa/logs/language_debug.log
[2025-07-30 23:44:07.082] [INFO    ] [PID:1181727-TID:140384139224896] [language_ops:125] [FUNC:setup_language_logging] ================================================================================
[2025-07-30 23:44:07.082] [INFO    ] [PID:1181727-TID:140384139224896] [language_ops.emergency_bot.telegram_bot.language_bridge:26] [FUNC:<module>] Language bridge module initialized with debug logging
[2025-07-30 23:45:37.059] [ERROR   ] [PID:1181727-TID:140384139224896] [language_ops.database:217] [FUNC:log_database_operation] DB_SELECT_FAILED: UserProfile for user 559773363 fields=['language'] - None
[2025-07-30 23:45:37.061] [INFO    ] [PID:1181727-TID:140384139224896] [language_ops.emergency_bot.telegram_bot.language_bridge:76] [FUNC:get_user_language_async] Retrieved language 'en' for user 559773363
[2025-07-30 23:46:43.542] [ERROR   ] [PID:1181727-TID:140384139224896] [language_ops.database:217] [FUNC:log_database_operation] DB_SELECT_FAILED: UserProfile for user 559773363 fields=['language'] - None
[2025-07-30 23:46:43.545] [INFO    ] [PID:1181727-TID:140384139224896] [language_ops.emergency_bot.telegram_bot.language_bridge:76] [FUNC:get_user_language_async] Retrieved language 'en' for user 559773363
[2025-07-30 23:46:44.733] [INFO    ] [PID:1181727-TID:140384139224896] [language_ops.emergency_bot.telegram_bot.language_bridge:172] [FUNC:language_button_callback] language_button_callback triggered by user 559773363 with data: setlang_om
[2025-07-30 23:46:44.751] [INFO    ] [PID:1181727-TID:140384139224896] [language_ops.emergency_bot.telegram_bot.language_bridge:201] [FUNC:language_button_callback] User 559773363 attempting to change language to: om
[2025-07-30 23:46:44.751] [INFO    ] [PID:1181727-TID:140384139224896] [language_ops.emergency_bot.telegram_bot.language_bridge:89] [FUNC:update_user_language_async] update_user_language_async called for user 559773363 with language om
[2025-07-30 23:46:44.751] [ERROR   ] [PID:1181727-TID:140384139224896] [language_ops.database:217] [FUNC:log_database_operation] DB_SELECT_FAILED: UserProfile for user 559773363 fields=['language'] - None
[2025-07-30 23:46:44.753] [INFO    ] [PID:1181727-TID:140384139224896] [language_ops.emergency_bot.telegram_bot.language_bridge:76] [FUNC:get_user_language_async] Retrieved language 'en' for user 559773363
[2025-07-30 23:46:44.754] [ERROR   ] [PID:1181727-TID:140384139224896] [language_ops.database:217] [FUNC:log_database_operation] DB_UPDATE_FAILED: UserProfile for user 559773363 fields=['language'] - None
[2025-07-30 23:46:44.755] [INFO    ] [PID:1181727-TID:140383811831552] [language_ops.emergency_bot.utils.translations:165] [FUNC:update_user_language] update_user_language called with telegram_id=559773363, language_code=om
[2025-07-30 23:46:44.756] [ERROR   ] [PID:1181727-TID:140383811831552] [language_ops.database:217] [FUNC:log_database_operation] DB_GET_OR_CREATE_FAILED: UserProfile for user 559773363 fields=['telegram_id', 'language'] - None
[2025-07-30 23:46:44.758] [INFO    ] [PID:1181727-TID:140383811831552] [language_ops.emergency_bot.utils.translations:226] [FUNC:update_user_language] Updating existing user 559773363 language from en to om
[2025-07-30 23:46:44.758] [ERROR   ] [PID:1181727-TID:140383811831552] [language_ops.database:217] [FUNC:log_database_operation] DB_UPDATE_FAILED: UserProfile for user 559773363 fields=['language'] - None
[2025-07-30 23:46:44.767] [INFO    ] [PID:1181727-TID:140383811831552] [language_ops.language_change:188] [FUNC:log_user_language_change] LANGUAGE_CHANGE_SUCCESS: User 559773363 changed from 'en' to 'om'
[2025-07-30 23:46:44.767] [INFO    ] [PID:1181727-TID:140383811831552] [language_ops.emergency_bot.utils.translations:242] [FUNC:update_user_language] Successfully updated language for user 559773363 from en to om
[2025-07-30 23:46:44.769] [INFO    ] [PID:1181727-TID:140384139224896] [language_ops.language_change:188] [FUNC:log_user_language_change] LANGUAGE_CHANGE_SUCCESS: User 559773363 changed from 'en' to 'om'
[2025-07-30 23:46:44.769] [INFO    ] [PID:1181727-TID:140384139224896] [language_ops.emergency_bot.telegram_bot.language_bridge:126] [FUNC:update_user_language_async] Successfully updated language for user 559773363 from en to om
[2025-07-30 23:46:44.769] [INFO    ] [PID:1181727-TID:140384139224896] [language_ops.emergency_bot.telegram_bot.language_bridge:206] [FUNC:language_button_callback] Language update result for user 559773363: success=True
[2025-07-30 23:46:44.769] [INFO    ] [PID:1181727-TID:140384139224896] [language_ops.emergency_bot.telegram_bot.language_bridge:209] [FUNC:language_button_callback] Language successfully updated to om for user 559773363
[2025-07-30 23:46:44.837] [INFO    ] [PID:1181727-TID:140384139224896] [language_ops.emergency_bot.telegram_bot.language_bridge:271] [FUNC:language_button_callback] Main menu sent successfully to user 559773363 in language om
[2025-07-30 23:46:52.453] [ERROR   ] [PID:1181727-TID:140384139224896] [language_ops.database:217] [FUNC:log_database_operation] DB_SELECT_FAILED: UserProfile for user 559773363 fields=['language'] - None
[2025-07-30 23:46:52.455] [INFO    ] [PID:1181727-TID:140384139224896] [language_ops.emergency_bot.telegram_bot.language_bridge:76] [FUNC:get_user_language_async] Retrieved language 'om' for user 559773363
[2025-07-30 23:46:53.516] [INFO    ] [PID:1181727-TID:140384139224896] [language_ops.emergency_bot.telegram_bot.language_bridge:172] [FUNC:language_button_callback] language_button_callback triggered by user 559773363 with data: setlang_am
[2025-07-30 23:46:53.573] [INFO    ] [PID:1181727-TID:140384139224896] [language_ops.emergency_bot.telegram_bot.language_bridge:201] [FUNC:language_button_callback] User 559773363 attempting to change language to: am
[2025-07-30 23:46:53.573] [INFO    ] [PID:1181727-TID:140384139224896] [language_ops.emergency_bot.telegram_bot.language_bridge:89] [FUNC:update_user_language_async] update_user_language_async called for user 559773363 with language am
[2025-07-30 23:46:53.574] [ERROR   ] [PID:1181727-TID:140384139224896] [language_ops.database:217] [FUNC:log_database_operation] DB_SELECT_FAILED: UserProfile for user 559773363 fields=['language'] - None
[2025-07-30 23:46:53.576] [INFO    ] [PID:1181727-TID:140384139224896] [language_ops.emergency_bot.telegram_bot.language_bridge:76] [FUNC:get_user_language_async] Retrieved language 'om' for user 559773363
[2025-07-30 23:46:53.576] [ERROR   ] [PID:1181727-TID:140384139224896] [language_ops.database:217] [FUNC:log_database_operation] DB_UPDATE_FAILED: UserProfile for user 559773363 fields=['language'] - None
[2025-07-30 23:46:53.577] [INFO    ] [PID:1181727-TID:140383811831552] [language_ops.emergency_bot.utils.translations:165] [FUNC:update_user_language] update_user_language called with telegram_id=559773363, language_code=am
[2025-07-30 23:46:53.577] [ERROR   ] [PID:1181727-TID:140383811831552] [language_ops.database:217] [FUNC:log_database_operation] DB_GET_OR_CREATE_FAILED: UserProfile for user 559773363 fields=['telegram_id', 'language'] - None
[2025-07-30 23:46:53.580] [INFO    ] [PID:1181727-TID:140383811831552] [language_ops.emergency_bot.utils.translations:226] [FUNC:update_user_language] Updating existing user 559773363 language from om to am
[2025-07-30 23:46:53.580] [ERROR   ] [PID:1181727-TID:140383811831552] [language_ops.database:217] [FUNC:log_database_operation] DB_UPDATE_FAILED: UserProfile for user 559773363 fields=['language'] - None
[2025-07-30 23:46:53.583] [INFO    ] [PID:1181727-TID:140383811831552] [language_ops.language_change:188] [FUNC:log_user_language_change] LANGUAGE_CHANGE_SUCCESS: User 559773363 changed from 'om' to 'am'
[2025-07-30 23:46:53.583] [INFO    ] [PID:1181727-TID:140383811831552] [language_ops.emergency_bot.utils.translations:242] [FUNC:update_user_language] Successfully updated language for user 559773363 from om to am
[2025-07-30 23:46:53.584] [INFO    ] [PID:1181727-TID:140384139224896] [language_ops.language_change:188] [FUNC:log_user_language_change] LANGUAGE_CHANGE_SUCCESS: User 559773363 changed from 'om' to 'am'
[2025-07-30 23:46:53.584] [INFO    ] [PID:1181727-TID:140384139224896] [language_ops.emergency_bot.telegram_bot.language_bridge:126] [FUNC:update_user_language_async] Successfully updated language for user 559773363 from om to am
[2025-07-30 23:46:53.585] [INFO    ] [PID:1181727-TID:140384139224896] [language_ops.emergency_bot.telegram_bot.language_bridge:206] [FUNC:language_button_callback] Language update result for user 559773363: success=True
[2025-07-30 23:46:53.585] [INFO    ] [PID:1181727-TID:140384139224896] [language_ops.emergency_bot.telegram_bot.language_bridge:209] [FUNC:language_button_callback] Language successfully updated to am for user 559773363
[2025-07-30 23:46:53.739] [INFO    ] [PID:1181727-TID:140384139224896] [language_ops.emergency_bot.telegram_bot.language_bridge:271] [FUNC:language_button_callback] Main menu sent successfully to user 559773363 in language am
[2025-07-30 23:46:59.255] [INFO    ] [PID:1188852-TID:140280007550784] [language_ops:120] [FUNC:setup_language_logging] ================================================================================
[2025-07-30 23:46:59.255] [INFO    ] [PID:1188852-TID:140280007550784] [language_ops:121] [FUNC:setup_language_logging] LANGUAGE DEBUG LOGGING INITIALIZED
[2025-07-30 23:46:59.255] [INFO    ] [PID:1188852-TID:140280007550784] [language_ops:122] [FUNC:setup_language_logging] Operations log: /home/hdmsofob/gaddisa/logs/language_operations.log
[2025-07-30 23:46:59.255] [INFO    ] [PID:1188852-TID:140280007550784] [language_ops:123] [FUNC:setup_language_logging] Error log: /home/hdmsofob/gaddisa/logs/language_errors.log
[2025-07-30 23:46:59.256] [INFO    ] [PID:1188852-TID:140280007550784] [language_ops:124] [FUNC:setup_language_logging] Debug log: /home/hdmsofob/gaddisa/logs/language_debug.log
[2025-07-30 23:46:59.256] [INFO    ] [PID:1188852-TID:140280007550784] [language_ops:125] [FUNC:setup_language_logging] ================================================================================
[2025-07-30 23:46:59.256] [INFO    ] [PID:1188852-TID:140280007550784] [language_ops.emergency_bot.telegram_bot.language_bridge:26] [FUNC:<module>] Language bridge module initialized with debug logging
[2025-07-30 23:47:06.190] [ERROR   ] [PID:1181727-TID:140384139224896] [language_ops.database:217] [FUNC:log_database_operation] DB_SELECT_FAILED: UserProfile for user 559773363 fields=['language'] - None
[2025-07-30 23:47:06.192] [INFO    ] [PID:1181727-TID:140384139224896] [language_ops.emergency_bot.telegram_bot.language_bridge:76] [FUNC:get_user_language_async] Retrieved language 'am' for user 559773363
[2025-07-30 23:47:08.047] [ERROR   ] [PID:1181727-TID:140384139224896] [language_ops.database:217] [FUNC:log_database_operation] DB_SELECT_FAILED: UserProfile for user 559773363 fields=['language'] - None
[2025-07-30 23:47:08.049] [INFO    ] [PID:1181727-TID:140384139224896] [language_ops.emergency_bot.telegram_bot.language_bridge:76] [FUNC:get_user_language_async] Retrieved language 'am' for user 559773363
[2025-07-30 23:47:10.456] [INFO    ] [PID:1193116-TID:140280007550784] [language_ops:120] [FUNC:setup_language_logging] ================================================================================
[2025-07-30 23:47:10.457] [INFO    ] [PID:1193116-TID:140280007550784] [language_ops:121] [FUNC:setup_language_logging] LANGUAGE DEBUG LOGGING INITIALIZED
[2025-07-30 23:47:10.457] [INFO    ] [PID:1193116-TID:140280007550784] [language_ops:122] [FUNC:setup_language_logging] Operations log: /home/hdmsofob/gaddisa/logs/language_operations.log
[2025-07-30 23:47:10.457] [INFO    ] [PID:1193116-TID:140280007550784] [language_ops:123] [FUNC:setup_language_logging] Error log: /home/hdmsofob/gaddisa/logs/language_errors.log
[2025-07-30 23:47:10.457] [INFO    ] [PID:1193116-TID:140280007550784] [language_ops:124] [FUNC:setup_language_logging] Debug log: /home/hdmsofob/gaddisa/logs/language_debug.log
[2025-07-30 23:47:10.457] [INFO    ] [PID:1193116-TID:140280007550784] [language_ops:125] [FUNC:setup_language_logging] ================================================================================
[2025-07-30 23:47:10.458] [INFO    ] [PID:1193116-TID:140280007550784] [language_ops.emergency_bot.telegram_bot.language_bridge:26] [FUNC:<module>] Language bridge module initialized with debug logging
[2025-07-31 00:13:43.695] [INFO    ] [PID:1299830-TID:140624003602240] [language_ops:120] [FUNC:setup_language_logging] ================================================================================
[2025-07-31 00:13:43.695] [INFO    ] [PID:1299830-TID:140624003602240] [language_ops:121] [FUNC:setup_language_logging] LANGUAGE DEBUG LOGGING INITIALIZED
[2025-07-31 00:13:43.695] [INFO    ] [PID:1299830-TID:140624003602240] [language_ops:122] [FUNC:setup_language_logging] Operations log: /home/hdmsofob/gaddisa/logs/language_operations.log
[2025-07-31 00:13:43.695] [INFO    ] [PID:1299830-TID:140624003602240] [language_ops:123] [FUNC:setup_language_logging] Error log: /home/hdmsofob/gaddisa/logs/language_errors.log
[2025-07-31 00:13:43.696] [INFO    ] [PID:1299830-TID:140624003602240] [language_ops:124] [FUNC:setup_language_logging] Debug log: /home/hdmsofob/gaddisa/logs/language_debug.log
[2025-07-31 00:13:43.696] [INFO    ] [PID:1299830-TID:140624003602240] [language_ops:125] [FUNC:setup_language_logging] ================================================================================
[2025-07-31 00:13:43.696] [INFO    ] [PID:1299830-TID:140624003602240] [language_ops.emergency_bot.telegram_bot.language_bridge:26] [FUNC:<module>] Language bridge module initialized with debug logging
[2025-07-31 00:14:01.570] [ERROR   ] [PID:1299830-TID:140624003602240] [language_ops.database:217] [FUNC:log_database_operation] DB_SELECT_FAILED: UserProfile for user 1841727454 fields=['language'] - None
[2025-07-31 00:14:01.571] [INFO    ] [PID:1299830-TID:140624003602240] [language_ops.emergency_bot.telegram_bot.language_bridge:76] [FUNC:get_user_language_async] Retrieved language 'en' for user 1841727454
[2025-07-31 00:14:07.518] [INFO    ] [PID:1299830-TID:140624003602240] [language_ops.emergency_bot.telegram_bot.language_bridge:172] [FUNC:language_button_callback] language_button_callback triggered by user 1841727454 with data: setlang_en
[2025-07-31 00:14:07.688] [INFO    ] [PID:1299830-TID:140624003602240] [language_ops.emergency_bot.telegram_bot.language_bridge:201] [FUNC:language_button_callback] User 1841727454 attempting to change language to: en
[2025-07-31 00:14:07.689] [INFO    ] [PID:1299830-TID:140624003602240] [language_ops.emergency_bot.telegram_bot.language_bridge:89] [FUNC:update_user_language_async] update_user_language_async called for user 1841727454 with language en
[2025-07-31 00:14:07.689] [ERROR   ] [PID:1299830-TID:140624003602240] [language_ops.database:217] [FUNC:log_database_operation] DB_SELECT_FAILED: UserProfile for user 1841727454 fields=['language'] - None
[2025-07-31 00:14:07.692] [INFO    ] [PID:1299830-TID:140624003602240] [language_ops.emergency_bot.telegram_bot.language_bridge:76] [FUNC:get_user_language_async] Retrieved language 'en' for user 1841727454
[2025-07-31 00:14:07.692] [INFO    ] [PID:1299830-TID:140624003602240] [language_ops.emergency_bot.telegram_bot.language_bridge:110] [FUNC:update_user_language_async] Language already set to en for user 1841727454, no update needed
[2025-07-31 00:14:07.693] [INFO    ] [PID:1299830-TID:140624003602240] [language_ops.language_change:188] [FUNC:log_user_language_change] LANGUAGE_CHANGE_SUCCESS: User 1841727454 changed from 'en' to 'en'
[2025-07-31 00:14:07.693] [INFO    ] [PID:1299830-TID:140624003602240] [language_ops.emergency_bot.telegram_bot.language_bridge:206] [FUNC:language_button_callback] Language update result for user 1841727454: success=True
[2025-07-31 00:14:07.693] [INFO    ] [PID:1299830-TID:140624003602240] [language_ops.emergency_bot.telegram_bot.language_bridge:209] [FUNC:language_button_callback] Language successfully updated to en for user 1841727454
[2025-07-31 00:14:07.865] [INFO    ] [PID:1299830-TID:140624003602240] [language_ops.emergency_bot.telegram_bot.language_bridge:271] [FUNC:language_button_callback] Main menu sent successfully to user 1841727454 in language en
[2025-07-31 00:14:11.897] [INFO    ] [PID:1301147-TID:140504554354496] [language_ops:120] [FUNC:setup_language_logging] ================================================================================
[2025-07-31 00:14:11.897] [INFO    ] [PID:1301147-TID:140504554354496] [language_ops:121] [FUNC:setup_language_logging] LANGUAGE DEBUG LOGGING INITIALIZED
[2025-07-31 00:14:11.897] [INFO    ] [PID:1301147-TID:140504554354496] [language_ops:122] [FUNC:setup_language_logging] Operations log: /home/hdmsofob/gaddisa/logs/language_operations.log
[2025-07-31 00:14:11.898] [INFO    ] [PID:1301147-TID:140504554354496] [language_ops:123] [FUNC:setup_language_logging] Error log: /home/hdmsofob/gaddisa/logs/language_errors.log
[2025-07-31 00:14:11.898] [INFO    ] [PID:1301147-TID:140504554354496] [language_ops:124] [FUNC:setup_language_logging] Debug log: /home/hdmsofob/gaddisa/logs/language_debug.log
[2025-07-31 00:14:11.898] [INFO    ] [PID:1301147-TID:140504554354496] [language_ops:125] [FUNC:setup_language_logging] ================================================================================
[2025-07-31 00:14:11.898] [INFO    ] [PID:1301147-TID:140504554354496] [language_ops.emergency_bot.telegram_bot.language_bridge:26] [FUNC:<module>] Language bridge module initialized with debug logging
[2025-07-31 00:14:15.300] [ERROR   ] [PID:1299830-TID:140624003602240] [language_ops.database:217] [FUNC:log_database_operation] DB_SELECT_FAILED: UserProfile for user 1841727454 fields=['language'] - None
[2025-07-31 00:14:15.302] [INFO    ] [PID:1299830-TID:140624003602240] [language_ops.emergency_bot.telegram_bot.language_bridge:76] [FUNC:get_user_language_async] Retrieved language 'en' for user 1841727454
[2025-07-31 00:14:16.608] [INFO    ] [PID:1299830-TID:140624003602240] [language_ops.emergency_bot.telegram_bot.language_bridge:172] [FUNC:language_button_callback] language_button_callback triggered by user 1841727454 with data: setlang_om
[2025-07-31 00:14:16.625] [INFO    ] [PID:1299830-TID:140624003602240] [language_ops.emergency_bot.telegram_bot.language_bridge:201] [FUNC:language_button_callback] User 1841727454 attempting to change language to: om
[2025-07-31 00:14:16.626] [INFO    ] [PID:1299830-TID:140624003602240] [language_ops.emergency_bot.telegram_bot.language_bridge:89] [FUNC:update_user_language_async] update_user_language_async called for user 1841727454 with language om
[2025-07-31 00:14:16.627] [ERROR   ] [PID:1299830-TID:140624003602240] [language_ops.database:217] [FUNC:log_database_operation] DB_SELECT_FAILED: UserProfile for user 1841727454 fields=['language'] - None
[2025-07-31 00:14:16.629] [INFO    ] [PID:1299830-TID:140624003602240] [language_ops.emergency_bot.telegram_bot.language_bridge:76] [FUNC:get_user_language_async] Retrieved language 'en' for user 1841727454
[2025-07-31 00:14:16.629] [ERROR   ] [PID:1299830-TID:140624003602240] [language_ops.database:217] [FUNC:log_database_operation] DB_UPDATE_FAILED: UserProfile for user 1841727454 fields=['language'] - None
[2025-07-31 00:14:16.630] [INFO    ] [PID:1299830-TID:140623604610816] [language_ops.emergency_bot.utils.translations:165] [FUNC:update_user_language] update_user_language called with telegram_id=1841727454, language_code=om
[2025-07-31 00:14:16.631] [ERROR   ] [PID:1299830-TID:140623604610816] [language_ops.database:217] [FUNC:log_database_operation] DB_GET_OR_CREATE_FAILED: UserProfile for user 1841727454 fields=['telegram_id', 'language'] - None
[2025-07-31 00:14:16.633] [INFO    ] [PID:1299830-TID:140623604610816] [language_ops.emergency_bot.utils.translations:226] [FUNC:update_user_language] Updating existing user 1841727454 language from en to om
[2025-07-31 00:14:16.633] [ERROR   ] [PID:1299830-TID:140623604610816] [language_ops.database:217] [FUNC:log_database_operation] DB_UPDATE_FAILED: UserProfile for user 1841727454 fields=['language'] - None
[2025-07-31 00:14:16.637] [INFO    ] [PID:1299830-TID:140623604610816] [language_ops.language_change:188] [FUNC:log_user_language_change] LANGUAGE_CHANGE_SUCCESS: User 1841727454 changed from 'en' to 'om'
[2025-07-31 00:14:16.637] [INFO    ] [PID:1299830-TID:140623604610816] [language_ops.emergency_bot.utils.translations:242] [FUNC:update_user_language] Successfully updated language for user 1841727454 from en to om
[2025-07-31 00:14:16.639] [INFO    ] [PID:1299830-TID:140624003602240] [language_ops.language_change:188] [FUNC:log_user_language_change] LANGUAGE_CHANGE_SUCCESS: User 1841727454 changed from 'en' to 'om'
[2025-07-31 00:14:16.639] [INFO    ] [PID:1299830-TID:140624003602240] [language_ops.emergency_bot.telegram_bot.language_bridge:126] [FUNC:update_user_language_async] Successfully updated language for user 1841727454 from en to om
[2025-07-31 00:14:16.639] [INFO    ] [PID:1299830-TID:140624003602240] [language_ops.emergency_bot.telegram_bot.language_bridge:206] [FUNC:language_button_callback] Language update result for user 1841727454: success=True
[2025-07-31 00:14:16.639] [INFO    ] [PID:1299830-TID:140624003602240] [language_ops.emergency_bot.telegram_bot.language_bridge:209] [FUNC:language_button_callback] Language successfully updated to om for user 1841727454
[2025-07-31 00:14:16.715] [INFO    ] [PID:1299830-TID:140624003602240] [language_ops.emergency_bot.telegram_bot.language_bridge:271] [FUNC:language_button_callback] Main menu sent successfully to user 1841727454 in language om
[2025-07-31 00:14:23.365] [INFO    ] [PID:1301545-TID:140468176664384] [language_ops:120] [FUNC:setup_language_logging] ================================================================================
[2025-07-31 00:14:23.365] [INFO    ] [PID:1301545-TID:140468176664384] [language_ops:121] [FUNC:setup_language_logging] LANGUAGE DEBUG LOGGING INITIALIZED
[2025-07-31 00:14:23.365] [INFO    ] [PID:1301545-TID:140468176664384] [language_ops:122] [FUNC:setup_language_logging] Operations log: /home/hdmsofob/gaddisa/logs/language_operations.log
[2025-07-31 00:14:23.365] [INFO    ] [PID:1301545-TID:140468176664384] [language_ops:123] [FUNC:setup_language_logging] Error log: /home/hdmsofob/gaddisa/logs/language_errors.log
[2025-07-31 00:14:23.365] [INFO    ] [PID:1301545-TID:140468176664384] [language_ops:124] [FUNC:setup_language_logging] Debug log: /home/hdmsofob/gaddisa/logs/language_debug.log
[2025-07-31 00:14:23.366] [INFO    ] [PID:1301545-TID:140468176664384] [language_ops:125] [FUNC:setup_language_logging] ================================================================================
[2025-07-31 00:14:23.366] [INFO    ] [PID:1301545-TID:140468176664384] [language_ops.emergency_bot.telegram_bot.language_bridge:26] [FUNC:<module>] Language bridge module initialized with debug logging
[2025-07-31 00:18:05.311] [INFO    ] [PID:1315881-TID:139724287481664] [language_ops:120] [FUNC:setup_language_logging] ================================================================================
[2025-07-31 00:18:05.311] [INFO    ] [PID:1315881-TID:139724287481664] [language_ops:121] [FUNC:setup_language_logging] LANGUAGE DEBUG LOGGING INITIALIZED
[2025-07-31 00:18:05.311] [INFO    ] [PID:1315881-TID:139724287481664] [language_ops:122] [FUNC:setup_language_logging] Operations log: /home/hdmsofob/gaddisa/logs/language_operations.log
[2025-07-31 00:18:05.311] [INFO    ] [PID:1315881-TID:139724287481664] [language_ops:123] [FUNC:setup_language_logging] Error log: /home/hdmsofob/gaddisa/logs/language_errors.log
[2025-07-31 00:18:05.312] [INFO    ] [PID:1315881-TID:139724287481664] [language_ops:124] [FUNC:setup_language_logging] Debug log: /home/hdmsofob/gaddisa/logs/language_debug.log
[2025-07-31 00:18:05.312] [INFO    ] [PID:1315881-TID:139724287481664] [language_ops:125] [FUNC:setup_language_logging] ================================================================================
[2025-07-31 00:18:05.312] [INFO    ] [PID:1315881-TID:139724287481664] [language_ops.emergency_bot.telegram_bot.language_bridge:26] [FUNC:<module>] Language bridge module initialized with debug logging
[2025-07-31 00:18:19.184] [INFO    ] [PID:1316807-TID:140204632602432] [language_ops:120] [FUNC:setup_language_logging] ================================================================================
[2025-07-31 00:18:19.184] [INFO    ] [PID:1316807-TID:140204632602432] [language_ops:121] [FUNC:setup_language_logging] LANGUAGE DEBUG LOGGING INITIALIZED
[2025-07-31 00:18:19.184] [INFO    ] [PID:1316807-TID:140204632602432] [language_ops:122] [FUNC:setup_language_logging] Operations log: /home/hdmsofob/gaddisa/logs/language_operations.log
[2025-07-31 00:18:19.185] [INFO    ] [PID:1316807-TID:140204632602432] [language_ops:123] [FUNC:setup_language_logging] Error log: /home/hdmsofob/gaddisa/logs/language_errors.log
[2025-07-31 00:18:19.185] [INFO    ] [PID:1316807-TID:140204632602432] [language_ops:124] [FUNC:setup_language_logging] Debug log: /home/hdmsofob/gaddisa/logs/language_debug.log
[2025-07-31 00:18:19.185] [INFO    ] [PID:1316807-TID:140204632602432] [language_ops:125] [FUNC:setup_language_logging] ================================================================================
[2025-07-31 00:18:19.185] [INFO    ] [PID:1316807-TID:140204632602432] [language_ops.emergency_bot.telegram_bot.language_bridge:26] [FUNC:<module>] Language bridge module initialized with debug logging
[2025-07-31 00:18:28.279] [ERROR   ] [PID:1316807-TID:140204632602432] [language_ops.database:217] [FUNC:log_database_operation] DB_SELECT_FAILED: UserProfile for user 1841727454 fields=['language'] - None
[2025-07-31 00:18:28.285] [INFO    ] [PID:1316807-TID:140204632602432] [language_ops.emergency_bot.telegram_bot.language_bridge:76] [FUNC:get_user_language_async] Retrieved language 'om' for user 1841727454
[2025-07-31 00:18:29.505] [INFO    ] [PID:1316807-TID:140204632602432] [language_ops.emergency_bot.telegram_bot.language_bridge:172] [FUNC:language_button_callback] language_button_callback triggered by user 1841727454 with data: setlang_am
[2025-07-31 00:18:29.534] [INFO    ] [PID:1316807-TID:140204632602432] [language_ops.emergency_bot.telegram_bot.language_bridge:201] [FUNC:language_button_callback] User 1841727454 attempting to change language to: am
[2025-07-31 00:18:29.535] [INFO    ] [PID:1316807-TID:140204632602432] [language_ops.emergency_bot.telegram_bot.language_bridge:89] [FUNC:update_user_language_async] update_user_language_async called for user 1841727454 with language am
[2025-07-31 00:18:29.535] [ERROR   ] [PID:1316807-TID:140204632602432] [language_ops.database:217] [FUNC:log_database_operation] DB_SELECT_FAILED: UserProfile for user 1841727454 fields=['language'] - None
[2025-07-31 00:18:29.537] [INFO    ] [PID:1316807-TID:140204632602432] [language_ops.emergency_bot.telegram_bot.language_bridge:76] [FUNC:get_user_language_async] Retrieved language 'om' for user 1841727454
[2025-07-31 00:18:29.538] [ERROR   ] [PID:1316807-TID:140204632602432] [language_ops.database:217] [FUNC:log_database_operation] DB_UPDATE_FAILED: UserProfile for user 1841727454 fields=['language'] - None
[2025-07-31 00:18:29.539] [INFO    ] [PID:1316807-TID:140204236998400] [language_ops.emergency_bot.utils.translations:165] [FUNC:update_user_language] update_user_language called with telegram_id=1841727454, language_code=am
[2025-07-31 00:18:29.540] [ERROR   ] [PID:1316807-TID:140204236998400] [language_ops.database:217] [FUNC:log_database_operation] DB_GET_OR_CREATE_FAILED: UserProfile for user 1841727454 fields=['telegram_id', 'language'] - None
[2025-07-31 00:18:29.542] [INFO    ] [PID:1316807-TID:140204236998400] [language_ops.emergency_bot.utils.translations:226] [FUNC:update_user_language] Updating existing user 1841727454 language from om to am
[2025-07-31 00:18:29.542] [ERROR   ] [PID:1316807-TID:140204236998400] [language_ops.database:217] [FUNC:log_database_operation] DB_UPDATE_FAILED: UserProfile for user 1841727454 fields=['language'] - None
[2025-07-31 00:18:29.544] [INFO    ] [PID:1316807-TID:140204236998400] [language_ops.language_change:188] [FUNC:log_user_language_change] LANGUAGE_CHANGE_SUCCESS: User 1841727454 changed from 'om' to 'am'
[2025-07-31 00:18:29.544] [INFO    ] [PID:1316807-TID:140204236998400] [language_ops.emergency_bot.utils.translations:242] [FUNC:update_user_language] Successfully updated language for user 1841727454 from om to am
[2025-07-31 00:18:29.546] [INFO    ] [PID:1316807-TID:140204632602432] [language_ops.language_change:188] [FUNC:log_user_language_change] LANGUAGE_CHANGE_SUCCESS: User 1841727454 changed from 'om' to 'am'
[2025-07-31 00:18:29.546] [INFO    ] [PID:1316807-TID:140204632602432] [language_ops.emergency_bot.telegram_bot.language_bridge:126] [FUNC:update_user_language_async] Successfully updated language for user 1841727454 from om to am
[2025-07-31 00:18:29.547] [INFO    ] [PID:1316807-TID:140204632602432] [language_ops.emergency_bot.telegram_bot.language_bridge:206] [FUNC:language_button_callback] Language update result for user 1841727454: success=True
[2025-07-31 00:18:29.547] [INFO    ] [PID:1316807-TID:140204632602432] [language_ops.emergency_bot.telegram_bot.language_bridge:209] [FUNC:language_button_callback] Language successfully updated to am for user 1841727454
[2025-07-31 00:18:29.636] [INFO    ] [PID:1316807-TID:140204632602432] [language_ops.emergency_bot.telegram_bot.language_bridge:271] [FUNC:language_button_callback] Main menu sent successfully to user 1841727454 in language am
[2025-07-31 00:22:56.338] [ERROR   ] [PID:1316807-TID:140204632602432] [language_ops.database:217] [FUNC:log_database_operation] DB_SELECT_FAILED: UserProfile for user 559773363 fields=['language'] - None
[2025-07-31 00:22:56.341] [INFO    ] [PID:1316807-TID:140204632602432] [language_ops.emergency_bot.telegram_bot.language_bridge:76] [FUNC:get_user_language_async] Retrieved language 'am' for user 559773363
[2025-07-31 00:22:57.445] [INFO    ] [PID:1316807-TID:140204632602432] [language_ops.emergency_bot.telegram_bot.language_bridge:172] [FUNC:language_button_callback] language_button_callback triggered by user 559773363 with data: setlang_am
[2025-07-31 00:22:57.509] [INFO    ] [PID:1316807-TID:140204632602432] [language_ops.emergency_bot.telegram_bot.language_bridge:201] [FUNC:language_button_callback] User 559773363 attempting to change language to: am
[2025-07-31 00:22:57.509] [INFO    ] [PID:1316807-TID:140204632602432] [language_ops.emergency_bot.telegram_bot.language_bridge:89] [FUNC:update_user_language_async] update_user_language_async called for user 559773363 with language am
[2025-07-31 00:22:57.510] [ERROR   ] [PID:1316807-TID:140204632602432] [language_ops.database:217] [FUNC:log_database_operation] DB_SELECT_FAILED: UserProfile for user 559773363 fields=['language'] - None
[2025-07-31 00:22:57.511] [INFO    ] [PID:1316807-TID:140204632602432] [language_ops.emergency_bot.telegram_bot.language_bridge:76] [FUNC:get_user_language_async] Retrieved language 'am' for user 559773363
[2025-07-31 00:22:57.512] [INFO    ] [PID:1316807-TID:140204632602432] [language_ops.emergency_bot.telegram_bot.language_bridge:110] [FUNC:update_user_language_async] Language already set to am for user 559773363, no update needed
[2025-07-31 00:22:57.512] [INFO    ] [PID:1316807-TID:140204632602432] [language_ops.language_change:188] [FUNC:log_user_language_change] LANGUAGE_CHANGE_SUCCESS: User 559773363 changed from 'am' to 'am'
[2025-07-31 00:22:57.512] [INFO    ] [PID:1316807-TID:140204632602432] [language_ops.emergency_bot.telegram_bot.language_bridge:206] [FUNC:language_button_callback] Language update result for user 559773363: success=True
[2025-07-31 00:22:57.512] [INFO    ] [PID:1316807-TID:140204632602432] [language_ops.emergency_bot.telegram_bot.language_bridge:209] [FUNC:language_button_callback] Language successfully updated to am for user 559773363
[2025-07-31 00:22:57.637] [INFO    ] [PID:1316807-TID:140204632602432] [language_ops.emergency_bot.telegram_bot.language_bridge:271] [FUNC:language_button_callback] Main menu sent successfully to user 559773363 in language am
[2025-07-31 00:22:58.555] [ERROR   ] [PID:1316807-TID:140204632602432] [language_ops.database:217] [FUNC:log_database_operation] DB_SELECT_FAILED: UserProfile for user 559773363 fields=['language'] - None
[2025-07-31 00:22:58.557] [INFO    ] [PID:1316807-TID:140204632602432] [language_ops.emergency_bot.telegram_bot.language_bridge:76] [FUNC:get_user_language_async] Retrieved language 'am' for user 559773363
[2025-07-31 00:22:59.333] [INFO    ] [PID:1316807-TID:140204632602432] [language_ops.emergency_bot.telegram_bot.language_bridge:172] [FUNC:language_button_callback] language_button_callback triggered by user 559773363 with data: setlang_om
[2025-07-31 00:22:59.350] [INFO    ] [PID:1316807-TID:140204632602432] [language_ops.emergency_bot.telegram_bot.language_bridge:201] [FUNC:language_button_callback] User 559773363 attempting to change language to: om
[2025-07-31 00:22:59.350] [INFO    ] [PID:1316807-TID:140204632602432] [language_ops.emergency_bot.telegram_bot.language_bridge:89] [FUNC:update_user_language_async] update_user_language_async called for user 559773363 with language om
[2025-07-31 00:22:59.351] [ERROR   ] [PID:1316807-TID:140204632602432] [language_ops.database:217] [FUNC:log_database_operation] DB_SELECT_FAILED: UserProfile for user 559773363 fields=['language'] - None
[2025-07-31 00:22:59.352] [INFO    ] [PID:1316807-TID:140204632602432] [language_ops.emergency_bot.telegram_bot.language_bridge:76] [FUNC:get_user_language_async] Retrieved language 'am' for user 559773363
[2025-07-31 00:22:59.352] [ERROR   ] [PID:1316807-TID:140204632602432] [language_ops.database:217] [FUNC:log_database_operation] DB_UPDATE_FAILED: UserProfile for user 559773363 fields=['language'] - None
[2025-07-31 00:22:59.353] [INFO    ] [PID:1316807-TID:140204236998400] [language_ops.emergency_bot.utils.translations:165] [FUNC:update_user_language] update_user_language called with telegram_id=559773363, language_code=om
[2025-07-31 00:22:59.354] [ERROR   ] [PID:1316807-TID:140204236998400] [language_ops.database:217] [FUNC:log_database_operation] DB_GET_OR_CREATE_FAILED: UserProfile for user 559773363 fields=['telegram_id', 'language'] - None
[2025-07-31 00:22:59.356] [INFO    ] [PID:1316807-TID:140204236998400] [language_ops.emergency_bot.utils.translations:226] [FUNC:update_user_language] Updating existing user 559773363 language from am to om
[2025-07-31 00:22:59.357] [ERROR   ] [PID:1316807-TID:140204236998400] [language_ops.database:217] [FUNC:log_database_operation] DB_UPDATE_FAILED: UserProfile for user 559773363 fields=['language'] - None
[2025-07-31 00:22:59.362] [INFO    ] [PID:1316807-TID:140204236998400] [language_ops.language_change:188] [FUNC:log_user_language_change] LANGUAGE_CHANGE_SUCCESS: User 559773363 changed from 'am' to 'om'
[2025-07-31 00:22:59.362] [INFO    ] [PID:1316807-TID:140204236998400] [language_ops.emergency_bot.utils.translations:242] [FUNC:update_user_language] Successfully updated language for user 559773363 from am to om
[2025-07-31 00:22:59.364] [INFO    ] [PID:1316807-TID:140204632602432] [language_ops.language_change:188] [FUNC:log_user_language_change] LANGUAGE_CHANGE_SUCCESS: User 559773363 changed from 'am' to 'om'
[2025-07-31 00:22:59.364] [INFO    ] [PID:1316807-TID:140204632602432] [language_ops.emergency_bot.telegram_bot.language_bridge:126] [FUNC:update_user_language_async] Successfully updated language for user 559773363 from am to om
[2025-07-31 00:22:59.364] [INFO    ] [PID:1316807-TID:140204632602432] [language_ops.emergency_bot.telegram_bot.language_bridge:206] [FUNC:language_button_callback] Language update result for user 559773363: success=True
[2025-07-31 00:22:59.364] [INFO    ] [PID:1316807-TID:140204632602432] [language_ops.emergency_bot.telegram_bot.language_bridge:209] [FUNC:language_button_callback] Language successfully updated to om for user 559773363
[2025-07-31 00:22:59.438] [INFO    ] [PID:1316807-TID:140204632602432] [language_ops.emergency_bot.telegram_bot.language_bridge:271] [FUNC:language_button_callback] Main menu sent successfully to user 559773363 in language om
[2025-07-31 01:00:35.959] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops:120] [FUNC:setup_language_logging] ================================================================================
[2025-07-31 01:00:35.959] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops:121] [FUNC:setup_language_logging] LANGUAGE DEBUG LOGGING INITIALIZED
[2025-07-31 01:00:35.960] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops:122] [FUNC:setup_language_logging] Operations log: /home/hdmsofob/gaddisa/logs/language_operations.log
[2025-07-31 01:00:35.960] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops:123] [FUNC:setup_language_logging] Error log: /home/hdmsofob/gaddisa/logs/language_errors.log
[2025-07-31 01:00:35.960] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops:124] [FUNC:setup_language_logging] Debug log: /home/hdmsofob/gaddisa/logs/language_debug.log
[2025-07-31 01:00:35.960] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops:125] [FUNC:setup_language_logging] ================================================================================
[2025-07-31 01:00:35.961] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops.emergency_bot.telegram_bot.language_bridge:26] [FUNC:<module>] Language bridge module initialized with debug logging
[2025-07-31 01:00:47.528] [ERROR   ] [PID:1476174-TID:139830719899456] [language_ops.database:217] [FUNC:log_database_operation] DB_SELECT_FAILED: UserProfile for user 559773363 fields=['language'] - None
[2025-07-31 01:00:47.530] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops.emergency_bot.telegram_bot.language_bridge:76] [FUNC:get_user_language_async] Retrieved language 'om' for user 559773363
[2025-07-31 01:00:49.309] [ERROR   ] [PID:1476174-TID:139830719899456] [language_ops.database:217] [FUNC:log_database_operation] DB_SELECT_FAILED: UserProfile for user 559773363 fields=['language'] - None
[2025-07-31 01:00:49.311] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops.emergency_bot.telegram_bot.language_bridge:76] [FUNC:get_user_language_async] Retrieved language 'om' for user 559773363
[2025-07-31 01:00:50.752] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops.emergency_bot.telegram_bot.language_bridge:172] [FUNC:language_button_callback] language_button_callback triggered by user 559773363 with data: setlang_am
[2025-07-31 01:00:50.770] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops.emergency_bot.telegram_bot.language_bridge:201] [FUNC:language_button_callback] User 559773363 attempting to change language to: am
[2025-07-31 01:00:50.770] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops.emergency_bot.telegram_bot.language_bridge:89] [FUNC:update_user_language_async] update_user_language_async called for user 559773363 with language am
[2025-07-31 01:00:50.770] [ERROR   ] [PID:1476174-TID:139830719899456] [language_ops.database:217] [FUNC:log_database_operation] DB_SELECT_FAILED: UserProfile for user 559773363 fields=['language'] - None
[2025-07-31 01:00:50.773] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops.emergency_bot.telegram_bot.language_bridge:76] [FUNC:get_user_language_async] Retrieved language 'om' for user 559773363
[2025-07-31 01:00:50.773] [ERROR   ] [PID:1476174-TID:139830719899456] [language_ops.database:217] [FUNC:log_database_operation] DB_UPDATE_FAILED: UserProfile for user 559773363 fields=['language'] - None
[2025-07-31 01:00:50.775] [INFO    ] [PID:1476174-TID:139830392506112] [language_ops.emergency_bot.utils.translations:165] [FUNC:update_user_language] update_user_language called with telegram_id=559773363, language_code=am
[2025-07-31 01:00:50.775] [ERROR   ] [PID:1476174-TID:139830392506112] [language_ops.database:217] [FUNC:log_database_operation] DB_GET_OR_CREATE_FAILED: UserProfile for user 559773363 fields=['telegram_id', 'language'] - None
[2025-07-31 01:00:50.778] [INFO    ] [PID:1476174-TID:139830392506112] [language_ops.emergency_bot.utils.translations:226] [FUNC:update_user_language] Updating existing user 559773363 language from om to am
[2025-07-31 01:00:50.778] [ERROR   ] [PID:1476174-TID:139830392506112] [language_ops.database:217] [FUNC:log_database_operation] DB_UPDATE_FAILED: UserProfile for user 559773363 fields=['language'] - None
[2025-07-31 01:00:50.782] [INFO    ] [PID:1476174-TID:139830392506112] [language_ops.language_change:188] [FUNC:log_user_language_change] LANGUAGE_CHANGE_SUCCESS: User 559773363 changed from 'om' to 'am'
[2025-07-31 01:00:50.782] [INFO    ] [PID:1476174-TID:139830392506112] [language_ops.emergency_bot.utils.translations:242] [FUNC:update_user_language] Successfully updated language for user 559773363 from om to am
[2025-07-31 01:00:50.784] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops.language_change:188] [FUNC:log_user_language_change] LANGUAGE_CHANGE_SUCCESS: User 559773363 changed from 'om' to 'am'
[2025-07-31 01:00:50.785] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops.emergency_bot.telegram_bot.language_bridge:126] [FUNC:update_user_language_async] Successfully updated language for user 559773363 from om to am
[2025-07-31 01:00:50.785] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops.emergency_bot.telegram_bot.language_bridge:206] [FUNC:language_button_callback] Language update result for user 559773363: success=True
[2025-07-31 01:00:50.785] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops.emergency_bot.telegram_bot.language_bridge:209] [FUNC:language_button_callback] Language successfully updated to am for user 559773363
[2025-07-31 01:00:50.874] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops.emergency_bot.telegram_bot.language_bridge:271] [FUNC:language_button_callback] Main menu sent successfully to user 559773363 in language am
[2025-07-31 01:00:53.802] [INFO    ] [PID:1478236-TID:140577562236736] [language_ops:120] [FUNC:setup_language_logging] ================================================================================
[2025-07-31 01:00:53.813] [INFO    ] [PID:1478236-TID:140577562236736] [language_ops:121] [FUNC:setup_language_logging] LANGUAGE DEBUG LOGGING INITIALIZED
[2025-07-31 01:00:53.813] [INFO    ] [PID:1478236-TID:140577562236736] [language_ops:122] [FUNC:setup_language_logging] Operations log: /home/hdmsofob/gaddisa/logs/language_operations.log
[2025-07-31 01:00:53.814] [INFO    ] [PID:1478236-TID:140577562236736] [language_ops:123] [FUNC:setup_language_logging] Error log: /home/hdmsofob/gaddisa/logs/language_errors.log
[2025-07-31 01:00:53.814] [INFO    ] [PID:1478236-TID:140577562236736] [language_ops:124] [FUNC:setup_language_logging] Debug log: /home/hdmsofob/gaddisa/logs/language_debug.log
[2025-07-31 01:00:53.814] [INFO    ] [PID:1478236-TID:140577562236736] [language_ops:125] [FUNC:setup_language_logging] ================================================================================
[2025-07-31 01:00:53.814] [INFO    ] [PID:1478236-TID:140577562236736] [language_ops.emergency_bot.telegram_bot.language_bridge:26] [FUNC:<module>] Language bridge module initialized with debug logging
[2025-07-31 01:00:54.345] [INFO    ] [PID:1478416-TID:140577562236736] [language_ops:120] [FUNC:setup_language_logging] ================================================================================
[2025-07-31 01:00:54.346] [INFO    ] [PID:1478416-TID:140577562236736] [language_ops:121] [FUNC:setup_language_logging] LANGUAGE DEBUG LOGGING INITIALIZED
[2025-07-31 01:00:54.346] [INFO    ] [PID:1478416-TID:140577562236736] [language_ops:122] [FUNC:setup_language_logging] Operations log: /home/hdmsofob/gaddisa/logs/language_operations.log
[2025-07-31 01:00:54.346] [INFO    ] [PID:1478416-TID:140577562236736] [language_ops:123] [FUNC:setup_language_logging] Error log: /home/hdmsofob/gaddisa/logs/language_errors.log
[2025-07-31 01:00:54.346] [INFO    ] [PID:1478416-TID:140577562236736] [language_ops:124] [FUNC:setup_language_logging] Debug log: /home/hdmsofob/gaddisa/logs/language_debug.log
[2025-07-31 01:00:54.347] [INFO    ] [PID:1478416-TID:140577562236736] [language_ops:125] [FUNC:setup_language_logging] ================================================================================
[2025-07-31 01:00:54.347] [INFO    ] [PID:1478416-TID:140577562236736] [language_ops.emergency_bot.telegram_bot.language_bridge:26] [FUNC:<module>] Language bridge module initialized with debug logging
[2025-07-31 01:01:50.553] [INFO    ] [PID:1484397-TID:140577562236736] [language_ops:120] [FUNC:setup_language_logging] ================================================================================
[2025-07-31 01:01:50.553] [INFO    ] [PID:1484397-TID:140577562236736] [language_ops:121] [FUNC:setup_language_logging] LANGUAGE DEBUG LOGGING INITIALIZED
[2025-07-31 01:01:50.553] [INFO    ] [PID:1484397-TID:140577562236736] [language_ops:122] [FUNC:setup_language_logging] Operations log: /home/hdmsofob/gaddisa/logs/language_operations.log
[2025-07-31 01:01:50.553] [INFO    ] [PID:1484397-TID:140577562236736] [language_ops:123] [FUNC:setup_language_logging] Error log: /home/hdmsofob/gaddisa/logs/language_errors.log
[2025-07-31 01:01:50.554] [INFO    ] [PID:1484397-TID:140577562236736] [language_ops:124] [FUNC:setup_language_logging] Debug log: /home/hdmsofob/gaddisa/logs/language_debug.log
[2025-07-31 01:01:50.554] [INFO    ] [PID:1484397-TID:140577562236736] [language_ops:125] [FUNC:setup_language_logging] ================================================================================
[2025-07-31 01:01:50.554] [INFO    ] [PID:1484397-TID:140577562236736] [language_ops.emergency_bot.telegram_bot.language_bridge:26] [FUNC:<module>] Language bridge module initialized with debug logging
[2025-07-31 01:02:01.642] [ERROR   ] [PID:1476174-TID:139830719899456] [language_ops.database:217] [FUNC:log_database_operation] DB_SELECT_FAILED: UserProfile for user 559773363 fields=['language'] - None
[2025-07-31 01:02:01.644] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops.emergency_bot.telegram_bot.language_bridge:76] [FUNC:get_user_language_async] Retrieved language 'am' for user 559773363
[2025-07-31 01:02:02.917] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops.emergency_bot.telegram_bot.language_bridge:172] [FUNC:language_button_callback] language_button_callback triggered by user 559773363 with data: setlang_om
[2025-07-31 01:02:02.942] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops.emergency_bot.telegram_bot.language_bridge:201] [FUNC:language_button_callback] User 559773363 attempting to change language to: om
[2025-07-31 01:02:02.942] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops.emergency_bot.telegram_bot.language_bridge:89] [FUNC:update_user_language_async] update_user_language_async called for user 559773363 with language om
[2025-07-31 01:02:02.943] [ERROR   ] [PID:1476174-TID:139830719899456] [language_ops.database:217] [FUNC:log_database_operation] DB_SELECT_FAILED: UserProfile for user 559773363 fields=['language'] - None
[2025-07-31 01:02:02.945] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops.emergency_bot.telegram_bot.language_bridge:76] [FUNC:get_user_language_async] Retrieved language 'am' for user 559773363
[2025-07-31 01:02:02.945] [ERROR   ] [PID:1476174-TID:139830719899456] [language_ops.database:217] [FUNC:log_database_operation] DB_UPDATE_FAILED: UserProfile for user 559773363 fields=['language'] - None
[2025-07-31 01:02:02.946] [INFO    ] [PID:1476174-TID:139830392506112] [language_ops.emergency_bot.utils.translations:165] [FUNC:update_user_language] update_user_language called with telegram_id=559773363, language_code=om
[2025-07-31 01:02:02.947] [ERROR   ] [PID:1476174-TID:139830392506112] [language_ops.database:217] [FUNC:log_database_operation] DB_GET_OR_CREATE_FAILED: UserProfile for user 559773363 fields=['telegram_id', 'language'] - None
[2025-07-31 01:02:02.949] [INFO    ] [PID:1476174-TID:139830392506112] [language_ops.emergency_bot.utils.translations:226] [FUNC:update_user_language] Updating existing user 559773363 language from am to om
[2025-07-31 01:02:02.949] [ERROR   ] [PID:1476174-TID:139830392506112] [language_ops.database:217] [FUNC:log_database_operation] DB_UPDATE_FAILED: UserProfile for user 559773363 fields=['language'] - None
[2025-07-31 01:02:02.953] [INFO    ] [PID:1476174-TID:139830392506112] [language_ops.language_change:188] [FUNC:log_user_language_change] LANGUAGE_CHANGE_SUCCESS: User 559773363 changed from 'am' to 'om'
[2025-07-31 01:02:02.953] [INFO    ] [PID:1476174-TID:139830392506112] [language_ops.emergency_bot.utils.translations:242] [FUNC:update_user_language] Successfully updated language for user 559773363 from am to om
[2025-07-31 01:02:02.954] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops.language_change:188] [FUNC:log_user_language_change] LANGUAGE_CHANGE_SUCCESS: User 559773363 changed from 'am' to 'om'
[2025-07-31 01:02:02.955] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops.emergency_bot.telegram_bot.language_bridge:126] [FUNC:update_user_language_async] Successfully updated language for user 559773363 from am to om
[2025-07-31 01:02:02.955] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops.emergency_bot.telegram_bot.language_bridge:206] [FUNC:language_button_callback] Language update result for user 559773363: success=True
[2025-07-31 01:02:02.955] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops.emergency_bot.telegram_bot.language_bridge:209] [FUNC:language_button_callback] Language successfully updated to om for user 559773363
[2025-07-31 01:02:03.039] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops.emergency_bot.telegram_bot.language_bridge:271] [FUNC:language_button_callback] Main menu sent successfully to user 559773363 in language om
[2025-07-31 01:02:05.941] [ERROR   ] [PID:1476174-TID:139830719899456] [language_ops.database:217] [FUNC:log_database_operation] DB_SELECT_FAILED: UserProfile for user 559773363 fields=['language'] - None
[2025-07-31 01:02:05.944] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops.emergency_bot.telegram_bot.language_bridge:76] [FUNC:get_user_language_async] Retrieved language 'om' for user 559773363
[2025-07-31 01:02:07.084] [ERROR   ] [PID:1476174-TID:139830719899456] [language_ops.database:217] [FUNC:log_database_operation] DB_SELECT_FAILED: UserProfile for user 559773363 fields=['language'] - None
[2025-07-31 01:02:07.086] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops.emergency_bot.telegram_bot.language_bridge:76] [FUNC:get_user_language_async] Retrieved language 'om' for user 559773363
[2025-07-31 07:53:27.182] [ERROR   ] [PID:1476174-TID:139830719899456] [language_ops.database:217] [FUNC:log_database_operation] DB_SELECT_FAILED: UserProfile for user 559773363 fields=['language'] - None
[2025-07-31 07:53:27.185] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops.emergency_bot.telegram_bot.language_bridge:76] [FUNC:get_user_language_async] Retrieved language 'om' for user 559773363
[2025-07-31 07:53:28.315] [ERROR   ] [PID:1476174-TID:139830719899456] [language_ops.database:217] [FUNC:log_database_operation] DB_SELECT_FAILED: UserProfile for user 559773363 fields=['language'] - None
[2025-07-31 07:53:28.317] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops.emergency_bot.telegram_bot.language_bridge:76] [FUNC:get_user_language_async] Retrieved language 'om' for user 559773363
[2025-07-31 07:53:29.627] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops.emergency_bot.telegram_bot.language_bridge:172] [FUNC:language_button_callback] language_button_callback triggered by user 559773363 with data: setlang_am
[2025-07-31 07:53:29.644] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops.emergency_bot.telegram_bot.language_bridge:201] [FUNC:language_button_callback] User 559773363 attempting to change language to: am
[2025-07-31 07:53:29.645] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops.emergency_bot.telegram_bot.language_bridge:89] [FUNC:update_user_language_async] update_user_language_async called for user 559773363 with language am
[2025-07-31 07:53:29.646] [ERROR   ] [PID:1476174-TID:139830719899456] [language_ops.database:217] [FUNC:log_database_operation] DB_SELECT_FAILED: UserProfile for user 559773363 fields=['language'] - None
[2025-07-31 07:53:29.649] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops.emergency_bot.telegram_bot.language_bridge:76] [FUNC:get_user_language_async] Retrieved language 'om' for user 559773363
[2025-07-31 07:53:29.649] [ERROR   ] [PID:1476174-TID:139830719899456] [language_ops.database:217] [FUNC:log_database_operation] DB_UPDATE_FAILED: UserProfile for user 559773363 fields=['language'] - None
[2025-07-31 07:53:29.650] [INFO    ] [PID:1476174-TID:139830392506112] [language_ops.emergency_bot.utils.translations:165] [FUNC:update_user_language] update_user_language called with telegram_id=559773363, language_code=am
[2025-07-31 07:53:29.651] [ERROR   ] [PID:1476174-TID:139830392506112] [language_ops.database:217] [FUNC:log_database_operation] DB_GET_OR_CREATE_FAILED: UserProfile for user 559773363 fields=['telegram_id', 'language'] - None
[2025-07-31 07:53:29.653] [INFO    ] [PID:1476174-TID:139830392506112] [language_ops.emergency_bot.utils.translations:226] [FUNC:update_user_language] Updating existing user 559773363 language from om to am
[2025-07-31 07:53:29.653] [ERROR   ] [PID:1476174-TID:139830392506112] [language_ops.database:217] [FUNC:log_database_operation] DB_UPDATE_FAILED: UserProfile for user 559773363 fields=['language'] - None
[2025-07-31 07:53:29.656] [INFO    ] [PID:1476174-TID:139830392506112] [language_ops.language_change:188] [FUNC:log_user_language_change] LANGUAGE_CHANGE_SUCCESS: User 559773363 changed from 'om' to 'am'
[2025-07-31 07:53:29.656] [INFO    ] [PID:1476174-TID:139830392506112] [language_ops.emergency_bot.utils.translations:242] [FUNC:update_user_language] Successfully updated language for user 559773363 from om to am
[2025-07-31 07:53:29.657] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops.language_change:188] [FUNC:log_user_language_change] LANGUAGE_CHANGE_SUCCESS: User 559773363 changed from 'om' to 'am'
[2025-07-31 07:53:29.658] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops.emergency_bot.telegram_bot.language_bridge:126] [FUNC:update_user_language_async] Successfully updated language for user 559773363 from om to am
[2025-07-31 07:53:29.658] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops.emergency_bot.telegram_bot.language_bridge:206] [FUNC:language_button_callback] Language update result for user 559773363: success=True
[2025-07-31 07:53:29.658] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops.emergency_bot.telegram_bot.language_bridge:209] [FUNC:language_button_callback] Language successfully updated to am for user 559773363
[2025-07-31 07:53:29.715] [INFO    ] [PID:1476174-TID:139830719899456] [language_ops.emergency_bot.telegram_bot.language_bridge:271] [FUNC:language_button_callback] Main menu sent successfully to user 559773363 in language am
[2025-07-31 07:53:33.186] [INFO    ] [PID:3515794-TID:140716857182016] [language_ops:120] [FUNC:setup_language_logging] ================================================================================
[2025-07-31 07:53:33.187] [INFO    ] [PID:3515794-TID:140716857182016] [language_ops:121] [FUNC:setup_language_logging] LANGUAGE DEBUG LOGGING INITIALIZED
[2025-07-31 07:53:33.187] [INFO    ] [PID:3515794-TID:140716857182016] [language_ops:122] [FUNC:setup_language_logging] Operations log: /home/hdmsofob/gaddisa/logs/language_operations.log
[2025-07-31 07:53:33.187] [INFO    ] [PID:3515794-TID:140716857182016] [language_ops:123] [FUNC:setup_language_logging] Error log: /home/hdmsofob/gaddisa/logs/language_errors.log
[2025-07-31 07:53:33.187] [INFO    ] [PID:3515794-TID:140716857182016] [language_ops:124] [FUNC:setup_language_logging] Debug log: /home/hdmsofob/gaddisa/logs/language_debug.log
[2025-07-31 07:53:33.188] [INFO    ] [PID:3515794-TID:140716857182016] [language_ops:125] [FUNC:setup_language_logging] ================================================================================
[2025-07-31 07:53:33.188] [INFO    ] [PID:3515794-TID:140716857182016] [language_ops.emergency_bot.telegram_bot.language_bridge:26] [FUNC:<module>] Language bridge module initialized with debug logging
[2025-07-31 07:53:33.771] [INFO    ] [PID:3515810-TID:140716857182016] [language_ops:120] [FUNC:setup_language_logging] ================================================================================
[2025-07-31 07:53:33.771] [INFO    ] [PID:3515810-TID:140716857182016] [language_ops:121] [FUNC:setup_language_logging] LANGUAGE DEBUG LOGGING INITIALIZED
[2025-07-31 07:53:33.772] [INFO    ] [PID:3515810-TID:140716857182016] [language_ops:122] [FUNC:setup_language_logging] Operations log: /home/hdmsofob/gaddisa/logs/language_operations.log
[2025-07-31 07:53:33.772] [INFO    ] [PID:3515810-TID:140716857182016] [language_ops:123] [FUNC:setup_language_logging] Error log: /home/hdmsofob/gaddisa/logs/language_errors.log
[2025-07-31 07:53:33.772] [INFO    ] [PID:3515810-TID:140716857182016] [language_ops:124] [FUNC:setup_language_logging] Debug log: /home/hdmsofob/gaddisa/logs/language_debug.log
[2025-07-31 07:53:33.772] [INFO    ] [PID:3515810-TID:140716857182016] [language_ops:125] [FUNC:setup_language_logging] ================================================================================
[2025-07-31 07:53:33.772] [INFO    ] [PID:3515810-TID:140716857182016] [language_ops.emergency_bot.telegram_bot.language_bridge:26] [FUNC:<module>] Language bridge module initialized with debug logging
[2025-08-04 05:31:57.911] [INFO    ] [PID:17552-TID:18788] [language_ops:120] [FUNC:setup_language_logging] ================================================================================
[2025-08-04 05:31:57.936] [INFO    ] [PID:17552-TID:18788] [language_ops:121] [FUNC:setup_language_logging] LANGUAGE DEBUG LOGGING INITIALIZED
[2025-08-04 05:31:57.936] [INFO    ] [PID:17552-TID:18788] [language_ops:122] [FUNC:setup_language_logging] Operations log: C:\Users\Kirubel\StudioProjects\gaddisa\logs\language_operations.log
[2025-08-04 05:31:57.936] [INFO    ] [PID:17552-TID:18788] [language_ops:123] [FUNC:setup_language_logging] Error log: C:\Users\Kirubel\StudioProjects\gaddisa\logs\language_errors.log
[2025-08-04 05:31:57.936] [INFO    ] [PID:17552-TID:18788] [language_ops:124] [FUNC:setup_language_logging] Debug log: C:\Users\Kirubel\StudioProjects\gaddisa\logs\language_debug.log
[2025-08-04 05:31:57.936] [INFO    ] [PID:17552-TID:18788] [language_ops:125] [FUNC:setup_language_logging] ================================================================================
[2025-08-04 05:31:57.936] [INFO    ] [PID:17552-TID:18788] [language_ops.emergency_bot.telegram_bot.language_bridge:26] [FUNC:<module>] Language bridge module initialized with debug logging
[2025-08-13 06:03:50.935] [INFO    ] [PID:9828-TID:10648] [language_ops:120] [FUNC:setup_language_logging] ================================================================================
[2025-08-13 06:03:50.978] [INFO    ] [PID:9828-TID:10648] [language_ops:121] [FUNC:setup_language_logging] LANGUAGE DEBUG LOGGING INITIALIZED
[2025-08-13 06:03:50.979] [INFO    ] [PID:9828-TID:10648] [language_ops:122] [FUNC:setup_language_logging] Operations log: C:\Users\Kirubel\StudioProjects\gaddisa\logs\language_operations.log
[2025-08-13 06:03:50.980] [INFO    ] [PID:9828-TID:10648] [language_ops:123] [FUNC:setup_language_logging] Error log: C:\Users\Kirubel\StudioProjects\gaddisa\logs\language_errors.log
[2025-08-13 06:03:50.980] [INFO    ] [PID:9828-TID:10648] [language_ops:124] [FUNC:setup_language_logging] Debug log: C:\Users\Kirubel\StudioProjects\gaddisa\logs\language_debug.log
[2025-08-13 06:03:50.981] [INFO    ] [PID:9828-TID:10648] [language_ops:125] [FUNC:setup_language_logging] ================================================================================
[2025-08-13 06:03:50.982] [INFO    ] [PID:9828-TID:10648] [language_ops.emergency_bot.telegram_bot.language_bridge:26] [FUNC:<module>] Language bridge module initialized with debug logging
[2025-08-13 06:04:05.516] [INFO    ] [PID:17276-TID:3768] [language_ops:120] [FUNC:setup_language_logging] ================================================================================
[2025-08-13 06:04:05.516] [INFO    ] [PID:17276-TID:3768] [language_ops:121] [FUNC:setup_language_logging] LANGUAGE DEBUG LOGGING INITIALIZED
[2025-08-13 06:04:05.517] [INFO    ] [PID:17276-TID:3768] [language_ops:122] [FUNC:setup_language_logging] Operations log: C:\Users\Kirubel\StudioProjects\gaddisa\logs\language_operations.log
[2025-08-13 06:04:05.518] [INFO    ] [PID:17276-TID:3768] [language_ops:123] [FUNC:setup_language_logging] Error log: C:\Users\Kirubel\StudioProjects\gaddisa\logs\language_errors.log
[2025-08-13 06:04:05.518] [INFO    ] [PID:17276-TID:3768] [language_ops:124] [FUNC:setup_language_logging] Debug log: C:\Users\Kirubel\StudioProjects\gaddisa\logs\language_debug.log
[2025-08-13 06:04:05.519] [INFO    ] [PID:17276-TID:3768] [language_ops:125] [FUNC:setup_language_logging] ================================================================================
[2025-08-13 06:04:05.520] [INFO    ] [PID:17276-TID:3768] [language_ops.emergency_bot.telegram_bot.language_bridge:26] [FUNC:<module>] Language bridge module initialized with debug logging
[2025-08-13 06:04:26.782] [INFO    ] [PID:8516-TID:9276] [language_ops:120] [FUNC:setup_language_logging] ================================================================================
[2025-08-13 06:04:26.810] [INFO    ] [PID:8516-TID:9276] [language_ops:121] [FUNC:setup_language_logging] LANGUAGE DEBUG LOGGING INITIALIZED
[2025-08-13 06:04:26.811] [INFO    ] [PID:8516-TID:9276] [language_ops:122] [FUNC:setup_language_logging] Operations log: C:\Users\Kirubel\StudioProjects\gaddisa\logs\language_operations.log
[2025-08-13 06:04:26.813] [INFO    ] [PID:8516-TID:9276] [language_ops:123] [FUNC:setup_language_logging] Error log: C:\Users\Kirubel\StudioProjects\gaddisa\logs\language_errors.log
[2025-08-13 06:04:26.813] [INFO    ] [PID:8516-TID:9276] [language_ops:124] [FUNC:setup_language_logging] Debug log: C:\Users\Kirubel\StudioProjects\gaddisa\logs\language_debug.log
[2025-08-13 06:04:26.814] [INFO    ] [PID:8516-TID:9276] [language_ops:125] [FUNC:setup_language_logging] ================================================================================
[2025-08-13 06:04:26.815] [INFO    ] [PID:8516-TID:9276] [language_ops.emergency_bot.telegram_bot.language_bridge:26] [FUNC:<module>] Language bridge module initialized with debug logging
[2025-08-13 06:04:48.114] [INFO    ] [PID:15640-TID:6624] [language_ops:120] [FUNC:setup_language_logging] ================================================================================
[2025-08-13 06:04:48.147] [INFO    ] [PID:15640-TID:6624] [language_ops:121] [FUNC:setup_language_logging] LANGUAGE DEBUG LOGGING INITIALIZED
[2025-08-13 06:04:48.148] [INFO    ] [PID:15640-TID:6624] [language_ops:122] [FUNC:setup_language_logging] Operations log: C:\Users\Kirubel\StudioProjects\gaddisa\logs\language_operations.log
[2025-08-13 06:04:48.149] [INFO    ] [PID:15640-TID:6624] [language_ops:123] [FUNC:setup_language_logging] Error log: C:\Users\Kirubel\StudioProjects\gaddisa\logs\language_errors.log
[2025-08-13 06:04:48.150] [INFO    ] [PID:15640-TID:6624] [language_ops:124] [FUNC:setup_language_logging] Debug log: C:\Users\Kirubel\StudioProjects\gaddisa\logs\language_debug.log
[2025-08-13 06:04:48.150] [INFO    ] [PID:15640-TID:6624] [language_ops:125] [FUNC:setup_language_logging] ================================================================================
[2025-08-13 06:04:48.151] [INFO    ] [PID:15640-TID:6624] [language_ops.emergency_bot.telegram_bot.language_bridge:26] [FUNC:<module>] Language bridge module initialized with debug logging
[2025-08-13 06:06:11.097] [INFO    ] [PID:17096-TID:7876] [language_ops:120] [FUNC:setup_language_logging] ================================================================================
[2025-08-13 06:06:11.213] [INFO    ] [PID:17096-TID:7876] [language_ops:121] [FUNC:setup_language_logging] LANGUAGE DEBUG LOGGING INITIALIZED
[2025-08-13 06:06:11.214] [INFO    ] [PID:17096-TID:7876] [language_ops:122] [FUNC:setup_language_logging] Operations log: C:\Users\Kirubel\StudioProjects\gaddisa\logs\language_operations.log
[2025-08-13 06:06:11.215] [INFO    ] [PID:17096-TID:7876] [language_ops:123] [FUNC:setup_language_logging] Error log: C:\Users\Kirubel\StudioProjects\gaddisa\logs\language_errors.log
[2025-08-13 06:06:11.215] [INFO    ] [PID:17096-TID:7876] [language_ops:124] [FUNC:setup_language_logging] Debug log: C:\Users\Kirubel\StudioProjects\gaddisa\logs\language_debug.log
[2025-08-13 06:06:11.216] [INFO    ] [PID:17096-TID:7876] [language_ops:125] [FUNC:setup_language_logging] ================================================================================
[2025-08-13 06:06:11.217] [INFO    ] [PID:17096-TID:7876] [language_ops.emergency_bot.telegram_bot.language_bridge:26] [FUNC:<module>] Language bridge module initialized with debug logging
[2025-08-13 06:06:33.645] [INFO    ] [PID:6512-TID:5980] [language_ops:120] [FUNC:setup_language_logging] ================================================================================
[2025-08-13 06:06:33.646] [INFO    ] [PID:6512-TID:5980] [language_ops:121] [FUNC:setup_language_logging] LANGUAGE DEBUG LOGGING INITIALIZED
[2025-08-13 06:06:33.647] [INFO    ] [PID:6512-TID:5980] [language_ops:122] [FUNC:setup_language_logging] Operations log: C:\Users\Kirubel\StudioProjects\gaddisa\logs\language_operations.log
[2025-08-13 06:06:34.559] [INFO    ] [PID:6512-TID:5980] [language_ops:123] [FUNC:setup_language_logging] Error log: C:\Users\Kirubel\StudioProjects\gaddisa\logs\language_errors.log
[2025-08-13 06:06:34.560] [INFO    ] [PID:6512-TID:5980] [language_ops:124] [FUNC:setup_language_logging] Debug log: C:\Users\Kirubel\StudioProjects\gaddisa\logs\language_debug.log
[2025-08-13 06:06:34.561] [INFO    ] [PID:6512-TID:5980] [language_ops:125] [FUNC:setup_language_logging] ================================================================================
[2025-08-13 06:06:34.562] [INFO    ] [PID:6512-TID:5980] [language_ops.emergency_bot.telegram_bot.language_bridge:26] [FUNC:<module>] Language bridge module initialized with debug logging
[2025-08-13 06:06:57.162] [INFO    ] [PID:992-TID:6624] [language_ops:120] [FUNC:setup_language_logging] ================================================================================
[2025-08-13 06:06:57.204] [INFO    ] [PID:992-TID:6624] [language_ops:121] [FUNC:setup_language_logging] LANGUAGE DEBUG LOGGING INITIALIZED
[2025-08-13 06:06:57.205] [INFO    ] [PID:992-TID:6624] [language_ops:122] [FUNC:setup_language_logging] Operations log: C:\Users\Kirubel\StudioProjects\gaddisa\logs\language_operations.log
[2025-08-13 06:06:57.205] [INFO    ] [PID:992-TID:6624] [language_ops:123] [FUNC:setup_language_logging] Error log: C:\Users\Kirubel\StudioProjects\gaddisa\logs\language_errors.log
[2025-08-13 06:06:57.206] [INFO    ] [PID:992-TID:6624] [language_ops:124] [FUNC:setup_language_logging] Debug log: C:\Users\Kirubel\StudioProjects\gaddisa\logs\language_debug.log
[2025-08-13 06:06:57.206] [INFO    ] [PID:992-TID:6624] [language_ops:125] [FUNC:setup_language_logging] ================================================================================
[2025-08-13 06:06:57.207] [INFO    ] [PID:992-TID:6624] [language_ops.emergency_bot.telegram_bot.language_bridge:26] [FUNC:<module>] Language bridge module initialized with debug logging
[2025-08-13 06:07:16.022] [INFO    ] [PID:76-TID:17184] [language_ops:120] [FUNC:setup_language_logging] ================================================================================
[2025-08-13 06:07:16.025] [INFO    ] [PID:76-TID:17184] [language_ops:121] [FUNC:setup_language_logging] LANGUAGE DEBUG LOGGING INITIALIZED
[2025-08-13 06:07:16.026] [INFO    ] [PID:76-TID:17184] [language_ops:122] [FUNC:setup_language_logging] Operations log: C:\Users\Kirubel\StudioProjects\gaddisa\logs\language_operations.log
[2025-08-13 06:07:16.027] [INFO    ] [PID:76-TID:17184] [language_ops:123] [FUNC:setup_language_logging] Error log: C:\Users\Kirubel\StudioProjects\gaddisa\logs\language_errors.log
[2025-08-13 06:07:16.028] [INFO    ] [PID:76-TID:17184] [language_ops:124] [FUNC:setup_language_logging] Debug log: C:\Users\Kirubel\StudioProjects\gaddisa\logs\language_debug.log
[2025-08-13 06:07:16.028] [INFO    ] [PID:76-TID:17184] [language_ops:125] [FUNC:setup_language_logging] ================================================================================
[2025-08-13 06:07:16.029] [INFO    ] [PID:76-TID:17184] [language_ops.emergency_bot.telegram_bot.language_bridge:26] [FUNC:<module>] Language bridge module initialized with debug logging
[2025-08-13 06:08:33.596] [INFO    ] [PID:8772-TID:6120] [language_ops:120] [FUNC:setup_language_logging] ================================================================================
[2025-08-13 06:08:33.597] [INFO    ] [PID:8772-TID:6120] [language_ops:121] [FUNC:setup_language_logging] LANGUAGE DEBUG LOGGING INITIALIZED
[2025-08-13 06:08:33.598] [INFO    ] [PID:8772-TID:6120] [language_ops:122] [FUNC:setup_language_logging] Operations log: C:\Users\Kirubel\StudioProjects\gaddisa\logs\language_operations.log
[2025-08-13 06:08:33.598] [INFO    ] [PID:8772-TID:6120] [language_ops:123] [FUNC:setup_language_logging] Error log: C:\Users\Kirubel\StudioProjects\gaddisa\logs\language_errors.log
[2025-08-13 06:08:33.599] [INFO    ] [PID:8772-TID:6120] [language_ops:124] [FUNC:setup_language_logging] Debug log: C:\Users\Kirubel\StudioProjects\gaddisa\logs\language_debug.log
[2025-08-13 06:08:33.601] [INFO    ] [PID:8772-TID:6120] [language_ops:125] [FUNC:setup_language_logging] ================================================================================
[2025-08-13 06:08:33.601] [INFO    ] [PID:8772-TID:6120] [language_ops.emergency_bot.telegram_bot.language_bridge:26] [FUNC:<module>] Language bridge module initialized with debug logging
